from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
app_path=ROOT/'src'/'App.jsx'; api_path=ROOT/'src'/'api.js'; main_path=ROOT/'src'/'main.jsx'
app=app_path.read_text(); api=api_path.read_text(); main=main_path.read_text()

api_anchor="  performanceReport: (params = {}) => request(`/admin/reports/performance?${new URLSearchParams(params)}`),\n"
if api_anchor not in api: raise SystemExit('performance API anchor missing')
if 'performanceInsights:' not in api:
    api=api.replace(api_anchor,api_anchor+"  performanceInsights: (params = {}) => request(`/admin/reports/performance-insights?${new URLSearchParams(params)}`),\n",1)
api_path.write_text(api)

old_state='''  const [data,setData]=useState(null);\n  const [targets,setTargets]=useState([]);\n  const [loading,setLoading]=useState(true);\n  const [error,setError]=useState("");'''
new_state='''  const [data,setData]=useState(null);\n  const [targets,setTargets]=useState([]);\n  const [insights,setInsights]=useState(null);\n  const [loading,setLoading]=useState(true);\n  const [error,setError]=useState("");'''
if old_state not in app: raise SystemExit('performance state anchor missing')
app=app.replace(old_state,new_state,1)

old_load='''    Promise.all([\n      api.performanceReport({period:"month",anchor,...(employee?{salesmanId:employee}:{})}),\n      api.performanceTargets({month:anchor})\n    ]).then(([p,t])=>{setData(p);setTargets(t.targets||[])}).catch(e=>setError(e.message||"Couldn't load performance.")).finally(()=>setLoading(false));'''
new_load='''    Promise.all([\n      api.performanceReport({period:"month",anchor,...(employee?{salesmanId:employee}:{})}),\n      api.performanceTargets({month:anchor}),\n      api.performanceInsights({month:anchor.slice(0,7),...(employee?{salesmanId:employee}:{})}).catch(()=>null)\n    ]).then(([p,t,i])=>{setData(p);setTargets(t.targets||[]);setInsights(i)}).catch(e=>setError(e.message||"Couldn't load performance.")).finally(()=>setLoading(false));'''
if old_load not in app: raise SystemExit('performance load anchor missing')
app=app.replace(old_load,new_load,1)

month_line='''  const monthLabel=new Date(`${anchor.slice(0,7)}-01T00:00:00`).toLocaleDateString("en-IN",{month:"long",year:"numeric"});'''
helpers=month_line+'''\n  const conversion=(a,b)=>Number(a)>0?Math.round(Number(b||0)/Number(a)*100):0;\n  const progressState=(r,tg)=>{\n    if(Number(r.leads||0)===0&&Number(r.visits||0)===0)return {label:"No activity",tone:"quiet"};\n    const p=(v,t)=>Number(t)>0?Math.round(Number(v||0)/Number(t)*100):null;\n    const won=p(r.won,tg.won_target), sales=p(r.sales_value,tg.sales_value_target), leads=p(r.leads,tg.leads_target), demos=p(r.demos,tg.demos_target);\n    if((won!=null&&won>=100)||(sales!=null&&sales>=100))return {label:"On target",tone:"strong"};\n    if(leads!=null&&demos!=null&&leads>=100&&demos>=100)return {label:"On track",tone:"strong"};\n    if([leads,demos,won].some(v=>v!=null)&&[leads,demos,won].filter(v=>v!=null).every(v=>v<60))return {label:"Behind",tone:"behind"};\n    if([leads,demos,won,sales].every(v=>v==null))return {label:"No target",tone:"quiet"};\n    return {label:"Active",tone:"active"};\n  };\n  const insightFor=id=>(insights?.employees||[]).find(x=>String(x.id||x.salesman_id)===String(id))||null;\n  const managerNotes=(r,tg,i)=>{const state=progressState(r,tg),notes=[];if(state.tone==='strong')notes.push('Strong progress against target this month.');else if(state.tone==='behind')notes.push('Core funnel activity is behind target and needs attention.');else if(state.tone==='quiet')notes.push('Very little recorded sales activity this month.');if(Number(i?.overdue_tasks||i?.tasks_overdue||0)>0)notes.push(`${Number(i?.overdue_tasks||i?.tasks_overdue)} overdue task${Number(i?.overdue_tasks||i?.tasks_overdue)===1?'':'s'} should be cleared.`);if(Number(i?.followups_overdue||i?.overdue_followups||0)>0)notes.push(`${Number(i?.followups_overdue||i?.overdue_followups)} follow-up${Number(i?.followups_overdue||i?.overdue_followups)===1?' is':'s are'} overdue.`);if(Number(i?.negotiations||0)>0)notes.push(`${Number(i.negotiations)} deal${Number(i.negotiations)===1?' is':'s are'} currently in negotiation.`);if(conversion(r.leads,r.won)>=25&&Number(r.won||0)>0)notes.push('Lead-to-win conversion is strong.');return notes.length?notes:['Performance is steady; keep activity and follow-ups consistent.'];};'''
if month_line not in app: raise SystemExit('performance month helper anchor missing')
app=app.replace(month_line,helpers,1)

old_header='''  return <div>\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:10,flexWrap:"wrap",marginBottom:15}}>\n      <div><div style={{fontSize:15,fontWeight:750,color:T.ink}}>Monthly performance & targets</div><div style={{fontSize:12,color:T.inkSoft,marginTop:3}}>{monthLabel} · Restaurant visits → Leads → Demos → Won → Sales value.</div></div>\n      <div style={{display:"flex",gap:7}}>'''
new_header='''  return <div className="engage-performance-report-page">\n    <div className="engage-performance-hero" style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:10,flexWrap:"wrap",marginBottom:15}}>\n      <div><div className="engage-performance-kicker">SALES PERFORMANCE</div><div style={{fontSize:18,fontWeight:800,color:T.ink}}>Monthly Performance</div><div style={{fontSize:12,color:T.inkSoft,marginTop:3}}>{monthLabel} · Restaurant visits → Leads → Demos → Won → Sales value.</div></div>\n      <div className="engage-performance-filters" style={{display:"flex",gap:7}}>'''
if old_header not in app: raise SystemExit('performance header anchor missing')
app=app.replace(old_header,new_header,1)
filter_close='''        </select>\n      </div>\n    </div>\n    {error&&'''
filter_new='''        </select>\n        <button type="button" onClick={load} disabled={loading} style={{height:36,border:`1px solid ${T.line}`,borderRadius:9,padding:"0 11px",background:"#fff",color:T.route,fontWeight:750,cursor:"pointer"}}><RefreshCw size={13}/> Refresh</button>\n      </div>\n    </div>\n    {error&&'''
if filter_close not in app: raise SystemExit('performance filter close anchor missing')
app=app.replace(filter_close,filter_new,1)

summary_anchor='''      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(135px,1fr))",gap:8,marginBottom:17}}>'''
summary_new='''      <div className="engage-performance-funnel" style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:8,marginBottom:10}}>\n        {[["Leads",data.totals.leads],["Demos",data.totals.demos],["Won",data.totals.won],["Sales",money(data.totals.sales_value)]].map(([label,value],idx)=><div key={label} style={{background:"#F7FAF9",border:`1px solid ${T.line}`,borderRadius:10,padding:"9px 10px",position:"relative"}}><div style={{fontSize:9.5,color:T.inkSoft,fontWeight:800,textTransform:"uppercase"}}>{label}</div><strong style={{fontSize:16}}>{value}</strong>{idx<3&&<span style={{position:"absolute",right:-7,top:"50%",color:T.inkSoft}}>→</span>}</div>)}\n      </div>\n      <div className="engage-performance-summary" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(135px,1fr))",gap:8,marginBottom:17}}>'''
if summary_anchor not in app: raise SystemExit('performance summary anchor missing')
app=app.replace(summary_anchor,summary_new,1)

card_anchor='''        {data.rows.map(r=>{const tg=targetFor(r.id);return <div key={r.id} style={{background:"#fff",border:`1px solid ${T.line}`,borderRadius:14,padding:14,boxShadow:"0 1px 2px rgba(20,20,30,.03)"}}>\n          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}>\n            <div><div style={{fontSize:14,fontWeight:800,color:T.ink}}>{r.full_name}</div><div style={{fontSize:11.5,color:T.inkSoft,marginTop:2}}>{r.won} won · {money(r.sales_value)} sales</div></div>\n            <span style={{fontSize:10.5,color:T.inkSoft}}>Targets set in Employee Settings</span>\n          </div>'''
card_new='''        {data.rows.map(r=>{const tg=targetFor(r.id);const ins=insightFor(r.id);const state=progressState(r,tg);return <div key={r.id} className="engage-performance-employee-card" style={{background:"#fff",border:`1px solid ${T.line}`,borderRadius:14,padding:14,boxShadow:"0 1px 2px rgba(20,20,30,.03)"}}>\n          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}>\n            <div><div style={{fontSize:14,fontWeight:800,color:T.ink}}>{r.full_name}</div><div style={{fontSize:11.5,color:T.inkSoft,marginTop:2}}>{r.won} won · {money(r.sales_value)} sales</div></div>\n            <span className={`engage-performance-status is-${state.tone}`} style={{fontSize:10.5,fontWeight:800,padding:"4px 8px",borderRadius:999,background:state.tone==='strong'?"#E6F6EF":state.tone==='behind'?"#FBEAE8":"#F4F5F7",color:state.tone==='strong'?T.verified:state.tone==='behind'?T.danger:T.inkSoft}}>{state.label}</span>\n          </div>'''
if card_anchor not in app: raise SystemExit('performance employee card anchor missing')
app=app.replace(card_anchor,card_new,1)

incentive='''              return earned>0?<div style={{marginTop:12,padding:"9px 10px",borderRadius:9,background:"#F0F8F4",color:T.route,fontSize:12,fontWeight:750}}>Calculated incentive · {money(earned)}</div>:null;\n            })()}\n          </>'''
manager='''              return earned>0?<div style={{marginTop:12,padding:"9px 10px",borderRadius:9,background:"#F0F8F4",color:T.route,fontSize:12,fontWeight:750}}>Calculated incentive · {money(earned)}</div>:null;\n            })()}\n            <div className="engage-performance-at-glance" style={{marginTop:12,paddingTop:11,borderTop:`1px solid ${T.line}`}}>\n              <div style={{fontSize:10,textTransform:"uppercase",letterSpacing:.5,fontWeight:800,color:T.inkSoft,marginBottom:7}}>At a glance</div>\n              <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:6}}>\n                {[["Lead → Demo",`${conversion(r.leads,r.demos)}%`],["Demo → Won",`${conversion(r.demos,r.won)}%`],["Lead → Won",`${conversion(r.leads,r.won)}%`]].map(([l,v])=><div key={l} style={{background:"#F7FAF9",borderRadius:8,padding:"7px 8px"}}><strong style={{fontSize:13}}>{v}</strong><div style={{fontSize:9.5,color:T.inkSoft}}>{l}</div></div>)}\n              </div>\n              {ins&&<div className="engage-performance-manager" style={{marginTop:9,background:"#F8FAFC",borderRadius:9,padding:"9px 10px"}}>\n                <div style={{fontSize:10,fontWeight:800,color:T.inkSoft,textTransform:"uppercase",marginBottom:6}}>Manager view</div>\n                <div style={{display:"flex",gap:8,flexWrap:"wrap",fontSize:10.5,color:T.inkSoft}}><span>{Number(ins.followups_completed||0)} follow-ups completed</span><span>{Number(ins.followups_overdue||ins.overdue_followups||0)} overdue</span><span>{Number(ins.negotiations||0)} negotiations</span><span>{Number(ins.active_days||0)} active days</span><span>{Number(ins.visits||r.visits||0)} visits</span></div>\n                <ul style={{margin:"7px 0 0",paddingLeft:17,fontSize:10.8,color:T.ink,lineHeight:1.45}}>{managerNotes(r,tg,ins).map((note,i)=><li key={i}>{note}</li>)}</ul>\n              </div>}\n            </div>\n          </>'''
if incentive not in app: raise SystemExit('performance incentive anchor missing')
app=app.replace(incentive,manager,1)
app_path.write_text(app)

main=main.replace('import "./performanceReportEnhance.js";\n','').replace('import "./performanceInsightsEnhance.js";\n','')
main_path.write_text(main)
print('Batch 9 applied')
