import React,{useEffect,useRef,useState} from 'react';
import {api,getSession} from './api.js';
import {OnboardingDialog} from './Onboarding.jsx';
import './collections.css';
import './quotations.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=(n,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c}).format(Number(n));
const methods={upi:'UPI',bank:'Bank transfer',cash:'Cash',cheque:'Cheque',card:'Card',other:'Other',unspecified:'Not recorded'};
const periods={monthly:'Monthly',yearly:'Yearly',one_time:'One-time'};
const uuid=()=>crypto.randomUUID();
export function CollectionsEntry({initialKey=null,label='Payment collections'}){const [open,setOpen]=useState(false);return <><button type="button" className="ft-collections-entry" onClick={()=>setOpen(true)}>{label}</button>{open&&<CollectionsPanel initialKey={initialKey} onClose={()=>setOpen(false)}/>}</>}
export function QuoteCollection({record}){
 const [due,setDue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="ft-q-box"><h3>Payment collection</h3><p className="ft-ob-muted">Use the accepted price, modules and quantities. Existing lead payments are preserved. Creating an account does not record a payment.</p><label className="ft-ob-field">Balance due date (optional)<input type="date" disabled={busy} value={due} onChange={e=>setDue(e.target.value)}/></label><button className="ft-ob-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await api.collectionFromQuote(record.quote.id,{revision:record.current.revision,version:record.current.version,dueDate:due});window.dispatchEvent(new CustomEvent('fieldtrail:open-collections',{detail:{key:r.key}}))}catch(e){setError(e.message)}finally{setBusy(false)}}}>Create / open payment account</button>{error&&<p role="alert">{error}</p>}{record.quote.lead_id&&<p className="ft-ob-muted">The linked lead must be Won, with a deal value equal to this quotation total. Linked leads use INR.</p>}</section>;
}
export default function CollectionsPanel({onClose,initialKey=null}){
 const admin=getSession()?.role==='admin';
 const [key,setKey]=useState(initialKey),[data,setData]=useState(null),[record,setRecord]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState(''),[currency,setCurrency]=useState('INR'),[owner,setOwner]=useState(''),[employees,setEmployees]=useState([]),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[from,setFrom]=useState(today().slice(0,7)+'-01'),[to,setTo]=useState(today()),[receipt,setReceipt]=useState(null),[share,setShare]=useState(false),[phone,setPhone]=useState('');
 useEffect(()=>{let live=true;if(admin)api.adminSalesmen().then(r=>{if(live)setEmployees(r.salesmen||[])}).catch(()=>{});return()=>{live=false}},[admin]);
 useEffect(()=>{const t=setTimeout(()=>{setQuery(search);setOffset(0)},250);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{let live=true;setLoading(true);setError('');if(!key&&(!from||!to||from>to)){setError('Choose a valid date range.');setLoading(false);return}const promise=key?api.collection(key):api.collections({currency,owner,search:query,offset,from,to});promise.then(r=>{if(live){if(key)setRecord(r);else setData(r)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[key,currency,owner,query,offset,from,to,refresh]);
 const work=async fn=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const openReceipt=p=>work(async()=>{const r=await api.collectionReceipt(key,p.id);setReceipt({...r.receipt,id:p.id});setShare(false);let n=(r.receipt.customer.phone||'').replace(/\D/g,'');if(n.length===10&&r.receipt.currency==='INR')n='91'+n;setPhone(n)});
 const download=()=>work(async()=>{const b=await api.collectionReceiptPDF(key,receipt.id),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=receipt.number+'.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice('Receipt downloaded. Attach it manually in WhatsApp.');});
 const changed=()=>{setRefresh(v=>v+1);setNotice('Payment saved. Balance updated.');window.dispatchEvent(new Event('fieldtrail:payments-updated'))};
 const a=record?.account;
 return <OnboardingDialog wide={admin} title={receipt?'Payment receipt':key?'Customer payments':admin?'Payments':'Payment due'} onClose={onClose} busy={busy}><div className="ft-col ft-q">
 {(key||receipt)&&<button disabled={busy} onClick={()=>{if(receipt){setReceipt(null);setShare(false)}else{setKey(null);setRecord(null)}setNotice('')}}>← {receipt?'Back to payments':'All accounts'}</button>}
 {error&&<div role="alert" className="ft-ob-error">{error}<button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>}{notice&&<p role="status" className="ft-col-notice">{notice}</p>}
 {receipt?<><article className="ft-col-receipt"><h2>{receipt.company}</h2><p className="ft-ob-muted">PAYMENT RECEIPT · {receipt.number} · V{receipt.version}</p><h3>{receipt.customer.name}</h3>{receipt.quoteNumber&&<p>{receipt.quoteNumber} · R{receipt.quoteRevision}</p>}<strong className="ft-col-amount">{money(receipt.amount,receipt.currency)}</strong><p>Received with thanks</p>{[['Date (IST)',receipt.date],['Method',methods[receipt.method]],['Reference',receipt.reference||'Not provided'],['Recorded by',receipt.recordedBy]].map(([l,v])=><div className="ft-q-line" key={l}><span>{l}</span><strong>{v}</strong></div>)}<p className="ft-ob-muted">Acknowledgment of recorded payment · Not a tax invoice</p></article><div className="ft-ob-actions"><button disabled={busy} className="ft-ob-primary" onClick={download}>Download PDF</button><button disabled={busy} onClick={()=>setShare(v=>!v)}>WhatsApp</button></div>{share&&<section className="ft-q-box"><h3>Review WhatsApp message</h3><p>{receipt.text}</p><label className="ft-ob-field">Recipient number with country code<input type="tel" maxLength={15} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))}/></label>{/^[1-9]\d{7,14}$/.test(phone)?<a className="ft-ob-primary" href={`https://wa.me/${phone}?text=${encodeURIComponent(receipt.text)}`} target="_blank" rel="noopener noreferrer">Open WhatsApp</a>:<p>Enter a valid phone number.</p>}<p className="ft-ob-muted">Download the receipt, attach it in WhatsApp, then tap Send.</p></section>}</>:
 key?loading?<p>Loading account…</p>:a&&<><div className="ft-ob-heading"><h3>{a.customer.name}</h3><span className="ft-ob-badge">{a.pending<=0?'Paid in full':Number(a.paid)>0?'Partially paid':'Unpaid'}</span></div><p className="ft-ob-muted">{a.owner_name||'Unassigned'} · {a.quote_number?`${a.quote_number} / R${a.quote_revision}`:'Won lead'} · {a.customer.phone}</p><section className="ft-q-box">{a.snapshot.package&&[a.snapshot.package,...(a.snapshot.addons||[])].map((m,i)=><div key={i}><div className="ft-q-line"><strong>{m.name} × {m.quantity||1}</strong><span>{money(m.price*(m.quantity||1),a.currency)}</span></div><p className="ft-ob-muted">{periods[m.period]} · {m.features}</p></div>)}{a.snapshot.discountMinor>0&&<div className="ft-q-line"><span>Discount</span><span>−{money(a.snapshot.discountMinor/100,a.currency)}</span></div>}{a.snapshot.taxMinor>0&&<div className="ft-q-line"><span>Tax</span><span>{money(a.snapshot.taxMinor/100,a.currency)}</span></div>}<div className="ft-q-line"><span>Agreed total</span><strong>{money(a.total,a.currency)}</strong></div><div className="ft-q-line"><span>Received</span><strong>{money(a.paid,a.currency)}</strong></div><div className="ft-col-balance"><span>Outstanding balance</span><strong>{money(a.pending,a.currency)}</strong></div>{admin?<DueDate key={`${a.key}-${a.version}`} account={a} busy={busy} onSave={d=>work(async()=>{const r=await api.collectionDue(key,{dueDate:d,version:a.version});setKey(r.key);setRefresh(v=>v+1);setNotice('Due date saved.');})}/>:a.due_date&&<div className="ft-q-line"><span>Due date</span><strong>{a.due_date}</strong></div>}</section>
 {admin&&a.pending>0&&<PaymentForm key={a.key} account={a} busy={busy} onSave={body=>work(async()=>{await api.collectionPay(key,body);changed();})}/>}
 <section className="ft-q-box"><h3>Payment history</h3>{record.historyLimited&&<p className="ft-ob-muted">Showing the latest 100 payments.</p>}{!record.payments.length&&<p>No payments recorded yet.</p>}{record.payments.map(p=><PaymentRow key={p.id} payment={p} admin={admin} currency={a.currency} busy={busy} onReceipt={()=>openReceipt(p)} onEdit={body=>work(async()=>{await api.collectionEdit(key,p.id,{...body,version:p.version});changed();})} onDelete={()=>work(async()=>{await api.collectionDelete(key,p.id,{version:p.version});changed();})}/>)}</section></>:
 <><p className="ft-ob-muted">{admin?'All payment accounts · collections, pending balances and overdue payments':'Your payment due · read-only. Payment records are managed by Admin.'}</p><div className="ft-col-filters"><label className="ft-ob-field">Currency<select value={currency} onChange={e=>{setCurrency(e.target.value);setOffset(0)}}>{['INR','AED','SAR'].map(c=><option key={c}>{c}</option>)}</select></label>{admin&&<label className="ft-ob-field">Salesman<select value={owner} onChange={e=>{setOwner(e.target.value);setOffset(0)}}><option value="">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>}<label className="ft-ob-field">Payments received from · IST<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setOffset(0)}}/></label><label className="ft-ob-field">Through · IST<input type="date" value={to} onChange={e=>{setTo(e.target.value);setOffset(0)}}/></label></div><label className="ft-ob-field">Find customer<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="Business or phone"/></label>{loading?<p>Loading collections…</p>:data&&!error&&<><div className="ft-col-stats">{[['collected','Collected in range'],['pending','Outstanding'],['overdue','Overdue (included)']].map(([k,l])=><div key={k}><span>{l}</span><strong>{money(data.summary[k],currency)}</strong></div>)}</div>{data.accounts.map(c=><button className="ft-ob-customer" key={c.key} onClick={()=>{setKey(c.key);setRecord(null)}}><strong>{c.customer.name}</strong><span>{money(c.pending,c.currency)} pending</span><span className="ft-ob-muted">{c.owner_name||'Unassigned'} · {c.due_date?`Due ${c.due_date}`:'No due date'}{Number(c.overdue)>0?' · Overdue':''}</span></button>)}{!data.accounts.length&&<p>No matching accounts. Won leads with a deal value appear here; accepted quotations can also create accounts.</p>}<div className="ft-ob-actions">{offset>0&&<button onClick={()=>setOffset(v=>v-50)}>Previous</button>}{data.hasMore&&<button onClick={()=>setOffset(v=>v+50)}>Next</button>}</div>{admin&&<section className="ft-q-box"><h3>Collections by salesman</h3>{data.employees.map(e=><div className="ft-col-employee" key={e.assigned_to||'none'}><strong>{e.owner_name||'Unassigned'}</strong><span>Collected {money(e.collected,currency)}</span><span>Pending {money(e.pending,currency)}</span><span>Overdue {money(e.overdue,currency)}</span></div>)}</section>}</>}</>}
 </div></OnboardingDialog>;
}
function DueDate({account,busy,onSave}){const [date,setDate]=useState(account.due_date?.slice(0,10)||'');return <div><label className="ft-ob-field">Balance due date<input type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><button disabled={busy} onClick={()=>onSave(date)}>Save due date</button></div>}
function PaymentForm({account,busy,onSave}){
 const [amount,setAmount]=useState(''),[date,setDate]=useState(today()),[method,setMethod]=useState('upi'),[reference,setReference]=useState(''),[note,setNote]=useState('');const token=useRef(uuid()),lastPayload=useRef('');
 const payload=()=>({amount:Number(amount),paymentDate:date,method,reference,note});
 return <form className="ft-q-box" onSubmit={e=>{e.preventDefault();const b=payload(),json=JSON.stringify(b);if(lastPayload.current&&lastPayload.current!==json)token.current=uuid();lastPayload.current=json;onSave({...b,requestId:token.current});}}><h3>Record payment</h3><div className="ft-col-filters"><label className="ft-ob-field">Amount received ({account.currency})<input type="number" min="0.01" max={account.pending} step="0.01" required disabled={busy} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="ft-ob-field">Payment date · IST<input type="date" max={today()} required disabled={busy} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="ft-ob-field">Payment method<select value={method} disabled={busy} onChange={e=>setMethod(e.target.value)}>{Object.entries(methods).filter(([k])=>k!=='unspecified').map(([k,l])=><option value={k} key={k}>{l}</option>)}</select></label><label className="ft-ob-field">Transaction / receipt reference<input maxLength={100} disabled={busy} value={reference} onChange={e=>setReference(e.target.value)}/></label></div><label className="ft-ob-field">Internal note (optional)<input maxLength={1000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="ft-ob-primary" disabled={busy}>{busy?'Saving…':'Save payment'}</button><p className="ft-ob-muted">Record funds received. This does not charge the customer.</p></form>;
}
function PaymentRow({payment:p,admin,currency,busy,onReceipt,onEdit,onDelete}){const [edit,setEdit]=useState(false),[remove,setRemove]=useState(false),[amount,setAmount]=useState(p.amount),[note,setNote]=useState(p.note||'');useEffect(()=>{setAmount(p.amount);setNote(p.note||'');setEdit(false);setRemove(false)},[p.version]);return <div className="ft-col-payment"><div className="ft-q-line"><strong>{money(p.amount,currency)}</strong><span>{methods[p.method]}</span></div><p className="ft-ob-muted">{p.payment_date} · {p.recorded_by_name||'Former employee'} · SW-R-{String(p.receipt_number).padStart(5,'0')}</p>{p.reference&&<p>{p.reference}</p>}{p.note&&<p className="ft-ob-muted">Internal: {p.note}</p>}<div className="ft-ob-actions"><button disabled={busy} onClick={onReceipt}>View receipt</button>{admin&&<><button disabled={busy} onClick={()=>setEdit(v=>!v)}>Correct payment</button><button disabled={busy} onClick={()=>setRemove(true)}>Delete</button></>}</div>{edit&&<form onSubmit={e=>{e.preventDefault();onEdit({amount:Number(amount),note})}}><label className="ft-ob-field">Correct amount<input type="number" step="0.01" min="0.01" required disabled={busy} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="ft-ob-field">Internal note<input maxLength={1000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></label><p className="ft-ob-muted">Updates the receipt version. Previously shared PDFs do not change.</p><button disabled={busy}>Save correction</button></form>}{remove&&<div role="alert"><p>Delete this payment permanently? The balance will increase. Shared receipts remain with their recipients.</p><div className="ft-ob-actions"><button disabled={busy} onClick={()=>setRemove(false)}>Cancel</button><button disabled={busy} onClick={onDelete}>Delete permanently</button></div></div>}</div>}
