import React,{useEffect,useRef,useState} from 'react';
import {api,getSession} from './api.js';
import {voidAcceptedQuotation,voidPaymentAccount} from './collectionLifecycleApi.js';
import {OnboardingDialog} from './Onboarding.jsx';
import './collections.css';
import './quotations.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=(n,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c}).format(Number(n));
const methods={upi:'UPI',bank:'Bank transfer',cash:'Cash',cheque:'Cheque',card:'Card',other:'Other',unspecified:'Not recorded'};
const periods={monthly:'Monthly',yearly:'Yearly',one_time:'One-time'};
const uuid=()=>crypto.randomUUID();
const istDateTime=value=>value?new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}):'';
export function CollectionsEntry({initialKey=null,label='Payment collections'}){const [open,setOpen]=useState(false);return <><button type="button" className="ft-collections-entry" onClick={()=>setOpen(true)}>{label}</button>{open&&<CollectionsPanel initialKey={initialKey} onClose={()=>setOpen(false)}/>}</>}
export function QuoteCollection({record}){
 const admin=getSession()?.role==='admin';
 const [due,setDue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[voidOpen,setVoidOpen]=useState(false),[reason,setReason]=useState(''),[voided,setVoided]=useState(!!record.quote.cancelled_at);
 if(voided)return <section className="ft-q-box"><h3>Quotation voided</h3><p className="ft-ob-muted">This accepted quotation is retained for audit history. Its linked payment account, if created, is also voided and removed from active Payments.</p>{(record.quote.cancel_reason||reason)&&<p><strong>Reason:</strong> {record.quote.cancel_reason||reason}</p>}</section>;
 const voidQuote=async()=>{setBusy(true);setError('');try{await voidAcceptedQuotation(record.quote.id,{revision:record.current.revision,version:record.current.version,reason});setVoided(true);setVoidOpen(false);window.dispatchEvent(new Event('fieldtrail:payments-updated'));window.dispatchEvent(new Event('fieldtrail:quotation-cancelled'));}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="ft-q-box"><h3>Payment collection</h3><p className="ft-ob-muted">Use the accepted price, modules and quantities. Existing lead payments are preserved. Creating an account does not record a payment.</p><label className="ft-ob-field">Balance due date (optional)<input type="date" disabled={busy} value={due} onChange={e=>setDue(e.target.value)}/></label><div className="ft-ob-actions"><button className="ft-ob-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await api.collectionFromQuote(record.quote.id,{revision:record.current.revision,version:record.current.version,dueDate:due});window.dispatchEvent(new CustomEvent('fieldtrail:open-collections',{detail:{key:r.key}}))}catch(e){setError(e.message)}finally{setBusy(false)}}}>Create / open payment account</button>{admin&&<button className="ft-q-danger" disabled={busy} onClick={()=>setVoidOpen(true)}>Void quotation</button>}</div>{voidOpen&&<div className="ft-q-delete" role="alert"><h3>Void this accepted quotation?</h3><p>The quotation will remain in audit history. Any linked payment account will also be voided and removed from active Payments. Existing payment records and receipts will be retained under Voided.</p><label className="ft-ob-field">Void reason<textarea required minLength={5} maxLength={500} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why is this quotation being voided?"/></label><div className="ft-ob-actions"><button disabled={busy} onClick={()=>{setVoidOpen(false);setReason('')}}>Keep quotation</button><button className="ft-q-danger" disabled={busy||reason.trim().length<5} onClick={voidQuote}>Void quotation</button></div></div>}{error&&<p role="alert">{error}</p>}{record.quote.lead_id&&<p className="ft-ob-muted">The linked lead must be Won, with a deal value equal to this quotation total. The quotation currency must match the linked lead.</p>}</section>;
}
export default function CollectionsPanel({onClose,initialKey=null,embedded=false}){
 const admin=getSession()?.role==='admin';
 const [status,setStatus]=useState(admin?'all':'pending');
 const [key,setKey]=useState(initialKey),[data,setData]=useState(null),[record,setRecord]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState(''),[currency]=useState('INR'),[owner,setOwner]=useState(''),[employees,setEmployees]=useState([]),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[period,setPeriod]=useState('all'),[from,setFrom]=useState(today().slice(0,7)+'-01'),[to,setTo]=useState(today()),[receipt,setReceipt]=useState(null),[share,setShare]=useState(false),[phone,setPhone]=useState('');
 useEffect(()=>{let live=true;if(admin)api.adminSalesmen().then(r=>{if(live)setEmployees(r.salesmen||[])}).catch(()=>{});return()=>{live=false}},[admin]);
 useEffect(()=>{const t=setTimeout(()=>{setQuery(search);setOffset(0)},250);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{let live=true;setLoading(true);setError('');if(key)setRecord(null);if(!key&&period==='custom'&&(!from||!to||from>to)){setError('Choose a valid date range.');setLoading(false);return}const promise=key?api.collection(key):api.collections({currency,owner,search:query,offset,...(period==='custom'?{from,to}:{}),status});promise.then(r=>{if(live){if(key)setRecord(r);else setData(r)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[key,currency,owner,query,offset,period,from,to,status,refresh]);
 const work=async fn=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const openReceipt=p=>work(async()=>{const r=await api.collectionReceipt(key,p.id);setReceipt({...r.receipt,id:p.id});setShare(false);let n=(r.receipt.customer.phone||'').replace(/\D/g,'');if(n.length===10&&r.receipt.currency==='INR')n='91'+n;setPhone(n)});
 const download=()=>work(async()=>{const b=await api.collectionReceiptPDF(key,receipt.id),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=receipt.number+'.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice('Receipt downloaded. Attach it manually in WhatsApp.');});
 const changed=()=>{setRefresh(v=>v+1);setNotice('Payment saved. Balance updated.');window.dispatchEvent(new Event('fieldtrail:payments-updated'))};
 const a=record?.account;
 const accounts=(data?.accounts||[]).filter(c=>admin?((status==='all'&&!c.voided_at)||(status==='voided'&&!!c.voided_at)||(status==='pending'&&!c.voided_at&&Number(c.pending)>0&&Number(c.paid)===0)||(status==='partial'&&!c.voided_at&&Number(c.paid)>0&&Number(c.pending)>0)||(status==='overdue'&&!c.voided_at&&Number(c.overdue)>0)||(status==='paid'&&!c.voided_at&&Number(c.pending)<=0)):!c.voided_at&&Number(c.pending)>0);

 const content=<div className="ft-col ft-q">
 {(key||receipt)&&<button className="ft-col-back" disabled={busy} onClick={()=>{if(receipt){setReceipt(null);setShare(false)}else{setKey(null);setRecord(null)}setNotice('')}}>← {receipt?'Back to payments':'All accounts'}</button>}
 {error&&<div role="alert" className="ft-ob-error">{error}<button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>}{notice&&<p role="status" className="ft-col-notice">{notice}</p>}
 {receipt?<><article className="ft-col-receipt"><h2>{receipt.company}</h2><p className="ft-ob-muted">PAYMENT RECEIPT · {receipt.number} · V{receipt.version}</p><h3>{receipt.customer.name}</h3>{receipt.quoteNumber&&<p>{receipt.quoteNumber} · R{receipt.quoteRevision}</p>}<strong className="ft-col-amount">{money(receipt.amount,receipt.currency)}</strong><p>Received with thanks</p>{[['Date (IST)',receipt.date],['Method',methods[receipt.method]],['Reference',receipt.reference||'Not provided'],['Recorded by',receipt.recordedBy]].map(([l,v])=><div className="ft-q-line" key={l}><span>{l}</span><strong>{v}</strong></div>)}<p className="ft-ob-muted">Acknowledgment of recorded payment · Not a tax invoice</p></article><div className="ft-ob-actions"><button disabled={busy} className="ft-ob-primary" onClick={download}>Download PDF</button><button disabled={busy} onClick={()=>setShare(v=>!v)}>WhatsApp</button></div>{share&&<section className="ft-q-box"><h3>Review WhatsApp message</h3><p>{receipt.text}</p><label className="ft-ob-field">Recipient number with country code<input type="tel" maxLength={15} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))}/></label>{/^[1-9]\d{7,14}$/.test(phone)?<a className="ft-ob-primary" href={`https://wa.me/${phone}?text=${encodeURIComponent(receipt.text)}`} target="_blank" rel="noopener noreferrer">Open WhatsApp</a>:<p>Enter a valid number with country code.</p>}<p className="ft-ob-muted">Download the receipt, attach it in WhatsApp, then tap Send.</p></section>}</>:
 key?loading?<p>Loading account…</p>:a&&<><div className="ft-col-account-hero"><div><h3>{a.customer.name}</h3><p className="ft-col-account-meta">{a.owner_name||'Unassigned'} · {a.quote_number?`${a.quote_number} / R${a.quote_revision}`:'Won lead'} · {a.customer.phone}</p></div><span className="ft-col-state ft-col-hero-state">{a.voided_at?'Voided':a.pending<=0?'Paid in full':Number(a.paid)>0?'Partially paid':'Unpaid'}</span></div>
 {a.voided_at&&<section className="ft-q-box ft-q-delete"><h3>{a.quote_id?'Quotation & payment account voided':'Payment account voided'}</h3><p><strong>Reason:</strong> {a.void_reason}</p><p className="ft-ob-muted">Voided {istDateTime(a.voided_at)}{a.voided_by_name?` by ${a.voided_by_name}`:''}. Existing payments and receipts are retained for audit history. No new payment changes are allowed.</p></section>}
 <section className="ft-q-box ft-col-summary-card">{a.snapshot.package&&<div className="ft-col-package-details">{[a.snapshot.package,...(a.snapshot.addons||[])].map((m,i)=><div key={i}><div className="ft-q-line"><strong>{m.name} × {m.quantity||1}</strong><span>{money(m.price*(m.quantity||1),a.currency)}</span></div><p className="ft-ob-muted">{periods[m.period]} · {m.features}</p></div>)}{a.snapshot.discountMinor>0&&<div className="ft-q-line"><span>Discount</span><span>−{money(a.snapshot.discountMinor/100,a.currency)}</span></div>}{a.snapshot.taxMinor>0&&<div className="ft-q-line"><span>Tax</span><span>{money(a.snapshot.taxMinor/100,a.currency)}</span></div>}</div>}<div className="ft-col-account-summary"><div><span>Agreed total</span><strong>{money(a.total,a.currency)}</strong></div><div><span>Received</span><strong>{money(a.paid,a.currency)}</strong></div><div className="is-outstanding"><span>{a.voided_at?'Outstanding when voided':'Outstanding'}</span><strong>{money(a.pending,a.currency)}</strong></div></div></section>
 {!a.voided_at&&(admin?<DueDate key={`${a.key}-${a.version}`} account={a} busy={busy} onSave={d=>work(async()=>{const r=await api.collectionDue(key,{dueDate:d,version:a.version});setKey(r.key);setRefresh(v=>v+1);setNotice('Due date saved.');})}/>:a.due_date&&<section className="ft-q-box ft-col-due-card"><div><span>Balance due date</span><strong>{a.due_date}</strong></div></section>)}
 {admin&&!a.voided_at&&a.pending>0&&<PaymentForm key={a.key} account={a} busy={busy} onSave={body=>work(async()=>{await api.collectionPay(key,body);changed();})}/>} 
 {admin&&!a.voided_at&&a.id&&<VoidAccountAction account={a} busy={busy} onVoid={reason=>work(async()=>{await voidPaymentAccount(key,{version:a.version,reason});setKey(null);setRecord(null);setRefresh(v=>v+1);setNotice(a.quote_id?'Quotation voided. Its payment account was removed from active Payments; history is available under Voided.':'Payment account voided and removed from active Payments; history is available under Voided.');window.dispatchEvent(new Event('fieldtrail:payments-updated'))})}/>} 
 <section id="payment-history" className="ft-q-box ft-col-history"><h3>Payment history</h3>{record.historyLimited&&<p className="ft-ob-muted">Showing the latest 100 payments.</p>}{!record.payments.length&&<p>No payments recorded yet.</p>}{record.payments.map(p=><PaymentRow key={p.id} payment={p} admin={admin&&!a.voided_at} currency={a.currency} busy={busy} onReceipt={()=>openReceipt(p)} onEdit={body=>work(async()=>{await api.collectionEdit(key,p.id,{...body,version:p.version});changed();})} onDelete={()=>work(async()=>{await api.collectionDelete(key,p.id,{version:p.version});changed();})}/>)}</section></>:
 <><p className="ft-ob-muted">{admin?'Track collections, outstanding balances and payment history':'Customers with an outstanding balance. Payment records are managed by Admin.'}</p><div className="ft-col-filters">{admin&&<label className="ft-ob-field">Salesman<select value={owner} onChange={e=>{setOwner(e.target.value);setOffset(0)}}><option value="">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>}{admin&&<label className="ft-ob-field">Period<select value={period} onChange={e=>{setPeriod(e.target.value);setOffset(0)}}><option value="all">All time</option><option value="custom">Custom range</option></select></label>}{admin&&period==='custom'&&<><label className="ft-ob-field">Payments received from · IST<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setOffset(0)}}/></label><label className="ft-ob-field">Through · IST<input type="date" value={to} onChange={e=>{setTo(e.target.value);setOffset(0)}}/></label></>}</div>{admin&&<div className="ft-col-tabs" role="group" aria-label="Payment status">{[["all","All accounts"],["pending","Pending"],["partial","Partially paid"],["overdue","Overdue"],["paid","Paid"],["voided","Voided"]].map(([value,label])=><button key={value} type="button" aria-pressed={status===value} onClick={()=>{setStatus(value);setOffset(0)}}>{label}</button>)}</div>}<label className="ft-ob-field">Find customer<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="Business or phone"/></label>{loading?<p>Loading collections…</p>:data&&!error&&<><div className="ft-col-stats">{(admin?[['collected',period==='all'?'Collected · All time':'Collected in range'],['pending','Outstanding'],['overdue','Overdue']]:[['pending','Outstanding'],['overdue','Overdue']]).map(([k,l])=><div key={k}><span>{l}</span><strong>{money(data.summary[k],currency)}</strong></div>)}</div><p className="ft-col-scope">{admin?'Voided accounts do not appear in All accounts or active payment statuses and are excluded from outstanding, overdue and collection totals. Open Voided only when you need audit history.':'Overdue is included in your outstanding balance.'}</p>
{accounts.map(c=><button className="ft-ob-customer ft-col-account" key={c.key} onClick={()=>{setKey(c.key);setRecord(null)}}>
 <span className="ft-col-account-heading"><strong>{c.customer.name}</strong><span className={'ft-col-state '+(c.voided_at?'overdue':Number(c.pending)<=0?'paid':Number(c.overdue)>0?'overdue':'pending')}>{c.voided_at?'Voided':Number(c.pending)<=0?'Paid in full':Number(c.overdue)>0?'Overdue':Number(c.paid)>0?'Partially paid':'Unpaid'}</span></span>
 <span className="ft-ob-muted">{c.owner_name||'Unassigned'}{c.voided_at?' · Voided':c.due_date?` · Due ${c.due_date}`:''}</span>
 <span className="ft-col-account-money"><span>Total<strong>{money(c.total,c.currency)}</strong></span><span>Paid<strong>{money(c.paid,c.currency)}</strong></span><span>Remaining<strong>{money(c.pending,c.currency)}</strong></span></span>
</button>)}
{!accounts.length&&<div className="ft-col-empty"><strong>{!admin||status==='pending'?'No payments pending':status==='partial'?'No partially paid accounts found':status==='paid'?'No paid accounts found':status==='overdue'?'No overdue payments':status==='voided'?'No voided accounts':'No matching accounts'}</strong><p>{!admin?'No outstanding balances match your search.':status==='all'?'Won leads with a deal value and accepted quotation accounts appear here.':'Try another status or adjust your search.'}</p></div>}
<div className="ft-ob-actions">{offset>0&&<button disabled={loading} onClick={()=>setOffset(v=>v-50)}>Previous</button>}{data.hasMore&&<button disabled={loading} onClick={()=>setOffset(v=>v+50)}>Next</button>}</div>{admin&&<section className="ft-q-box"><h3>Collections by salesman</h3>{data.employees.map(e=><div className="ft-col-employee" key={e.assigned_to||'none'}><strong>{e.owner_name||'Unassigned'}</strong><span>Collected {money(e.collected,currency)}</span><span>Pending {money(e.pending,currency)}</span><span>Overdue {money(e.overdue,currency)}</span></div>)}</section>}</>}</>}
 </div>;
 return embedded?content:<OnboardingDialog wide={admin} title={receipt?'Payment receipt':key?'Customer payments':admin?'Payments':'Payment due'} onClose={onClose} busy={busy}>{content}</OnboardingDialog>;
}
function VoidAccountAction({account,busy,onVoid}){const [open,setOpen]=useState(false),[reason,setReason]=useState('');const linked=!!account.quote_id;return <section className="ft-q-box"><div className="ft-ob-heading"><div><h3>{linked?'Void quotation':'Void payment account'}</h3><p className="ft-ob-muted">{linked?'Voiding the accepted quotation also voids this payment account. It disappears from active Payments, while payments and receipts remain under Voided for audit.':'Voiding removes this account from active Payments while keeping payment and receipt history under Voided.'}</p></div>{!open&&<button className="ft-q-danger" disabled={busy} onClick={()=>setOpen(true)}>{linked?'Void quotation':'Void account'}</button>}</div>{open&&<><label className="ft-ob-field">Void reason<textarea minLength={5} maxLength={500} required disabled={busy} value={reason} onChange={e=>setReason(e.target.value)} placeholder={linked?'Why is this quotation being voided?':'Why is this payment account being voided?'}/></label><div className="ft-ob-actions"><button disabled={busy} onClick={()=>{setOpen(false);setReason('')}}>Keep active</button><button className="ft-q-danger" disabled={busy||reason.trim().length<5} onClick={()=>onVoid(reason.trim())}>{linked?'Void quotation':'Void payment account'}</button></div></>}</section>}
function DueDate({account,busy,onSave}){const [date,setDate]=useState(account.due_date?.slice(0,10)||'');return <section className="ft-q-box ft-col-due-card"><div className="ft-col-due-head"><div><span>Balance due date</span><strong>{date||'Not set'}</strong></div><span className="ft-col-due-hint">Keep collection follow-up clear</span></div><div className="ft-col-due-controls"><input aria-label="Balance due date" type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/><button disabled={busy} onClick={()=>onSave(date)}>{account.due_date?'Update due date':'Save due date'}</button></div></section>}
function PaymentForm({account,busy,onSave}){
 const [amount,setAmount]=useState(''),[date,setDate]=useState(today()),[method,setMethod]=useState('upi'),[reference,setReference]=useState(''),[note,setNote]=useState('');const token=useRef(uuid()),lastPayload=useRef('');
 const payload=()=>({amount:Number(amount),paymentDate:date,method,reference,note});
 return <form className="ft-q-box ft-col-payment-form" onSubmit={e=>{e.preventDefault();const b=payload(),json=JSON.stringify(b);if(lastPayload.current&&lastPayload.current!==json)token.current=uuid();lastPayload.current=json;onSave({...b,requestId:token.current});}}><div className="ft-col-form-head"><div><span>PAYMENT ENTRY</span><h3>Record Payment</h3></div><button type="button" className="ft-col-details-link" onClick={()=>document.getElementById('payment-history')?.scrollIntoView({behavior:'smooth',block:'start'})}>View details →</button></div><div className="ft-col-filters"><label className="ft-ob-field">Amount received ({new Intl.NumberFormat('en-IN',{style:'currency',currency:account.currency}).formatToParts(0).find(p=>p.type==='currency')?.value})<input type="number" min="0.01" max={account.pending} step="0.01" required disabled={busy} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="ft-ob-field">Payment date · IST<input type="date" max={today()} required disabled={busy} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="ft-ob-field">Payment method<select value={method} disabled={busy} onChange={e=>setMethod(e.target.value)}>{Object.entries(methods).filter(([k])=>k!=='unspecified').map(([k,l])=><option value={k} key={k}>{l}</option>)}</select></label><label className="ft-ob-field">Transaction / receipt reference<input maxLength={100} disabled={busy} value={reference} onChange={e=>setReference(e.target.value)}/></label></div><label className="ft-ob-field">Internal note (optional)<textarea rows="2" maxLength={1000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="ft-col-form-actions"><p className="ft-ob-muted">Record funds received. This does not charge the customer.</p><button className="ft-ob-primary" disabled={busy}>{busy?'Saving…':'Record payment'}</button></div></form>;
}
function PaymentRow({payment:p,admin,currency,busy,onReceipt,onEdit,onDelete}){const [edit,setEdit]=useState(false),[remove,setRemove]=useState(false),[amount,setAmount]=useState(p.amount),[note,setNote]=useState(p.note||'');useEffect(()=>{setAmount(p.amount);setNote(p.note||'');setEdit(false);setRemove(false)},[p.version]);return <div className="ft-col-payment"><div className="ft-q-line"><strong>{money(p.amount,currency)}</strong><span>{methods[p.method]}</span></div><p className="ft-ob-muted">{p.payment_date} · {p.recorded_by_name||'Former employee'} · SW-R-{String(p.receipt_number).padStart(5,'0')}</p>{p.reference&&<p>{p.reference}</p>}{p.note&&<p className="ft-ob-muted">Internal: {p.note}</p>}<div className="ft-ob-actions"><button disabled={busy} onClick={onReceipt}>View receipt</button>{admin&&<><button disabled={busy} onClick={()=>setEdit(v=>!v)}>Correct payment</button><button disabled={busy} onClick={()=>setRemove(true)}>Delete</button></>}</div>{edit&&<form onSubmit={e=>{e.preventDefault();onEdit({amount:Number(amount),note})}}><label className="ft-ob-field">Correct amount<input type="number" step="0.01" min="0.01" required disabled={busy} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="ft-ob-field">Internal note<input maxLength={1000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></label><p className="ft-ob-muted">Updates the receipt version. Previously shared PDFs do not change.</p><button disabled={busy}>Save correction</button></form>}{remove&&<div role="alert"><p>Delete this payment permanently? The balance will increase. Shared receipts remain with their recipients.</p><div className="ft-ob-actions"><button disabled={busy} onClick={()=>setRemove(false)}>Cancel</button><button disabled={busy} onClick={onDelete}>Delete permanently</button></div></div>}</div>}
