import { getApiBase, getSession } from './api.js';

const C={ink:'#1A1D23',soft:'#6B7280',line:'#E7E9EE',paper:'#F4F5F7',card:'#FFFFFF',green:'#12805C',greenSoft:'#E6F6EF',warn:'#B8791F',warnSoft:'#FDF3E0',danger:'#C0392B',dangerSoft:'#FBEAE8',route:'#145C5D',routeSoft:'#E7F1F1'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const close=()=>document.getElementById('engage-data-health-overlay')?.remove();

function buttonStyle(){return ['width:100%','display:flex','align-items:center','justify-content:center','gap:8px','padding:11px','border-radius:11px',`border:1px solid ${C.line}`,'cursor:pointer','background:#EDEEF2',`color:${C.ink}`,'font-weight:700','font-size:13.5px','margin-bottom:18px'].join(';')}
function authHeaders(){return {Authorization:`Bearer ${getSession()?.token||''}`}}
function severity(check){if(check.ok)return {label:'Healthy',color:C.green,bg:C.greenSoft,icon:'✓'};if(check.severity==='critical')return {label:'Critical',color:C.danger,bg:C.dangerSoft,icon:'!'};return {label:'Warning',color:C.warn,bg:C.warnSoft,icon:'•'}}
function fmtDate(v){if(!v)return '—';try{return new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}catch{return String(v)}}
function valueLabel(k,v){if(v==null)return '—';if(/_at$|time|started|finished|updated/.test(k)&&typeof v==='string')return fmtDate(v);if(typeof v==='boolean')return v?'Yes':'No';return String(v)}

async function fetchHealth(){const base=getApiBase(),s=getSession();if(!base||!s?.token)throw new Error('Admin session or backend URL is missing.');const r=await fetch(`${base}/admin/data-health`,{headers:authHeaders()});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Data Health request failed (${r.status})`);return d}
async function fetchDetails(key){const r=await fetch(`${getApiBase()}/admin/data-health/details/${encodeURIComponent(key)}`,{headers:authHeaders()});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||'Could not load affected records.');return d}

function renderDetails(container,data){const rows=data.rows||[];if(!rows.length){container.innerHTML=`<div style="padding:16px;text-align:center;color:${C.soft};font-size:12px">No affected records found.</div>`;return}
  container.innerHTML=rows.map((row,i)=>`<div style="padding:12px 13px;border-top:${i?`1px solid ${C.line}`:'none'};background:#fff">
    <div style="font-size:11px;font-weight:900;color:${C.ink};margin-bottom:7px">Record ${i+1}</div>
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:7px 12px">${Object.entries(row).filter(([,v])=>v!==null).map(([k,v])=>`<div><div style="font-size:9px;text-transform:uppercase;letter-spacing:.45px;font-weight:900;color:${C.soft}">${esc(pretty(k))}</div><div style="font-size:11.5px;color:${C.ink};margin-top:2px;word-break:break-word">${esc(valueLabel(k,v))}</div></div>`).join('')}</div>
  </div>`).join('')+(data.limited?`<div style="padding:9px 12px;background:${C.paper};font-size:10.5px;color:${C.soft};border-top:1px solid ${C.line}">Showing first 50 affected records.</div>`:'')}

function cardHtml(ch){const s=severity(ch);return `<div data-check-card data-key="${esc(ch.key)}" data-category="${esc(ch.category||'Other')}" data-state="${ch.ok?'healthy':ch.severity}" style="border:1px solid ${ch.ok?C.line:s.color+'55'};border-radius:14px;background:${ch.ok?'#fff':s.bg};overflow:hidden">
  <div style="display:flex;align-items:center;gap:11px;padding:13px 14px">
    <div style="width:29px;height:29px;min-width:29px;border-radius:9px;display:grid;place-items:center;background:${s.color};color:#fff;font-weight:900;font-size:13px">${s.icon}</div>
    <div style="min-width:0;flex:1"><div style="display:flex;gap:7px;align-items:center;flex-wrap:wrap"><div style="font-size:12.5px;font-weight:900;color:${C.ink}">${esc(ch.title||pretty(ch.key))}</div><span style="font-size:8.5px;font-weight:900;text-transform:uppercase;letter-spacing:.45px;color:${C.soft};background:#fff;border:1px solid ${C.line};border-radius:999px;padding:2px 6px">${esc(ch.category||'Other')}</span></div>
      <div style="font-size:10.8px;color:${C.soft};margin-top:3px;line-height:1.35">${esc(ch.why||'Backend integrity check')}</div>
    </div>
    <div style="text-align:right;min-width:64px"><div style="font-size:${ch.ok?12:20}px;font-weight:950;color:${s.color}">${ch.ok?'OK':Number(ch.count||0)}</div><div style="font-size:8.5px;font-weight:900;text-transform:uppercase;letter-spacing:.4px;color:${s.color};margin-top:1px">${s.label}</div></div>
  </div>
  ${!ch.ok&&ch.detailsAvailable?`<div style="padding:0 14px 12px"><button data-view-records="${esc(ch.key)}" style="border:1px solid ${s.color}55;background:#fff;color:${s.color};border-radius:8px;padding:6px 9px;font-size:10.5px;font-weight:900;cursor:pointer">View affected records →</button><div data-detail-box="${esc(ch.key)}" style="display:none;margin-top:9px;border:1px solid ${C.line};border-radius:10px;overflow:hidden;background:#fff"></div></div>`:''}
</div>`}

function render(body,data,error){if(error){body.innerHTML=`<div style="padding:18px;border-radius:12px;background:${C.dangerSoft};color:${C.danger};font-size:13px;font-weight:800">${esc(error)}</div>`;return}
 if(!data){body.innerHTML=`<div style="padding:42px;text-align:center"><div style="width:34px;height:34px;border:3px solid ${C.line};border-top-color:${C.route};border-radius:50%;margin:0 auto 12px;animation:dhspin .8s linear infinite"></div><div style="font-size:12px;color:${C.soft}">Running backend integrity checks…</div></div>`;return}
 const sm=data.summary||{},checks=data.checks||[],critical=Number(sm.critical||0),warning=Number(sm.warning||0),issueChecks=checks.filter(x=>!x.ok).length,healthy=checks.length-issueChecks;
 const overall=critical?{bg:C.dangerSoft,color:C.danger,title:'Critical data issues found',sub:'Some records can affect report or workflow accuracy.'}:warning?{bg:C.warnSoft,color:C.warn,title:'Backend healthy with warnings',sub:'Core data is safe, but some records should be reviewed.'}:{bg:C.greenSoft,color:C.green,title:'Everything looks healthy',sub:'No integrity issues detected in the checked areas.'};
 const cats=[...new Set(checks.map(x=>x.category||'Other'))];
 body.innerHTML=`<style>@keyframes dhspin{to{transform:rotate(360deg)}} .dh-tab.active{background:${C.ink}!important;color:#fff!important;border-color:${C.ink}!important}.dh-filter.active{background:${C.routeSoft}!important;color:${C.route}!important;border-color:${C.route}55!important}@media(max-width:620px){.dh-kpis{grid-template-columns:repeat(2,1fr)!important}.dh-system{grid-template-columns:1fr!important}.dh-toolbar{align-items:stretch!important;flex-direction:column!important}}</style>
  <div style="padding:17px 18px;border-radius:16px;background:${overall.bg};display:flex;align-items:flex-start;gap:12px;margin-bottom:14px">
    <div style="width:34px;height:34px;border-radius:11px;background:${overall.color};color:#fff;display:grid;place-items:center;font-size:17px;font-weight:950">${critical?'!':warning?'•':'✓'}</div>
    <div style="flex:1"><div style="font-size:15px;font-weight:950;color:${overall.color}">${overall.title}</div><div style="font-size:11.5px;color:${C.soft};margin-top:3px">${overall.sub}</div><div style="font-size:10px;color:${C.soft};margin-top:6px">Checked ${fmtDate(data.checkedAt)}</div></div>
  </div>
  <div class="dh-kpis" style="display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:14px">
    ${[['Checks',checks.length,C.ink],['Healthy',healthy,C.green],['Critical records',critical,critical?C.danger:C.green],['Warning records',warning,warning?C.warn:C.green]].map(([l,v,c])=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:12px;padding:11px 12px"><div style="font-size:9px;text-transform:uppercase;letter-spacing:.5px;font-weight:900;color:${C.soft}">${l}</div><div style="font-size:21px;font-weight:950;color:${c};margin-top:3px">${v}</div></div>`).join('')}
  </div>
  <div class="dh-system" style="display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:14px">
    <div style="background:#fff;border:1px solid ${C.line};border-radius:12px;padding:12px 13px"><div style="font-size:9px;text-transform:uppercase;letter-spacing:.45px;font-weight:900;color:${C.soft}">Database</div><div style="display:flex;align-items:center;gap:7px;margin-top:5px"><span style="width:8px;height:8px;border-radius:50%;background:${C.green}"></span><span style="font-size:12px;font-weight:850;color:${C.ink}">Connected</span></div></div>
    <div style="background:#fff;border:1px solid ${C.line};border-radius:12px;padding:12px 13px"><div style="font-size:9px;text-transform:uppercase;letter-spacing:.45px;font-weight:900;color:${C.soft}">Latest Migration</div><div style="font-size:11.5px;font-weight:850;color:${C.ink};margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis" title="${esc(data.system?.latestMigration?.filename||'')}">${esc(data.system?.latestMigration?.filename||'Unknown')}</div></div>
  </div>
  <div class="dh-toolbar" style="display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:11px">
    <div style="display:flex;gap:6px;flex-wrap:wrap"><button class="dh-tab active" data-tab="issues" style="border:1px solid ${C.line};background:#fff;border-radius:9px;padding:7px 10px;font-size:10.5px;font-weight:900;cursor:pointer">Needs attention (${issueChecks})</button><button class="dh-tab" data-tab="all" style="border:1px solid ${C.line};background:#fff;border-radius:9px;padding:7px 10px;font-size:10.5px;font-weight:900;cursor:pointer">All checks (${checks.length})</button><button class="dh-tab" data-tab="system" style="border:1px solid ${C.line};background:#fff;border-radius:9px;padding:7px 10px;font-size:10.5px;font-weight:900;cursor:pointer">System</button></div>
    <input data-dh-search placeholder="Search checks…" style="min-width:180px;border:1px solid ${C.line};border-radius:9px;padding:7px 9px;font:inherit;font-size:10.5px;outline:none;background:#fff" />
  </div>
  <div data-category-filters style="display:flex;gap:6px;overflow:auto;padding-bottom:8px;margin-bottom:4px"><button class="dh-filter active" data-category="all" style="white-space:nowrap;border:1px solid ${C.line};background:#fff;border-radius:999px;padding:5px 8px;font-size:9.5px;font-weight:850;cursor:pointer">All</button>${cats.map(x=>`<button class="dh-filter" data-category="${esc(x)}" style="white-space:nowrap;border:1px solid ${C.line};background:#fff;border-radius:999px;padding:5px 8px;font-size:9.5px;font-weight:850;cursor:pointer">${esc(x)}</button>`).join('')}</div>
  <div data-check-list style="display:flex;flex-direction:column;gap:8px">${checks.map(cardHtml).join('')}</div>
  <div data-system-panel style="display:none">
    <div style="border:1px solid ${C.line};background:#fff;border-radius:14px;overflow:hidden"><div style="padding:12px 14px;border-bottom:1px solid ${C.line};font-size:12.5px;font-weight:900;color:${C.ink}">Scheduled jobs</div>${(data.system?.jobs||[]).length?(data.system.jobs.map(j=>`<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;padding:11px 14px;border-top:1px solid ${C.line}"><div><div style="font-size:9px;color:${C.soft};font-weight:900;text-transform:uppercase">Job</div><div style="font-size:11px;font-weight:850;margin-top:2px">${esc(pretty(j.job_key))}</div></div><div><div style="font-size:9px;color:${C.soft};font-weight:900;text-transform:uppercase">Last success</div><div style="font-size:10.5px;margin-top:2px">${esc(fmtDate(j.last_success))}</div></div><div><div style="font-size:9px;color:${C.soft};font-weight:900;text-transform:uppercase">Last attempt</div><div style="font-size:10.5px;margin-top:2px">${esc(fmtDate(j.last_attempt))}</div></div></div>`).join('')):`<div style="padding:18px;color:${C.soft};font-size:11px">No scheduled-job history yet.</div>`}</div>
  </div>`;
 let tab='issues',cat='all',query='';
 const apply=()=>{const system=tab==='system';body.querySelector('[data-system-panel]').style.display=system?'block':'none';body.querySelector('[data-check-list]').style.display=system?'none':'flex';body.querySelector('[data-category-filters]').style.display=system?'none':'flex';body.querySelector('[data-dh-search]').style.display=system?'none':'block';body.querySelectorAll('[data-check-card]').forEach(el=>{const ch=checks.find(x=>x.key===el.dataset.key);const visible=!system&&(tab==='all'||!ch.ok)&&(cat==='all'||el.dataset.category===cat)&&(!query||(ch.title||pretty(ch.key)).toLowerCase().includes(query)||String(ch.why||'').toLowerCase().includes(query));el.style.display=visible?'block':'none'})};
 body.querySelectorAll('.dh-tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;body.querySelectorAll('.dh-tab').forEach(x=>x.classList.toggle('active',x===b));apply()});
 body.querySelectorAll('.dh-filter').forEach(b=>b.onclick=()=>{cat=b.dataset.category;body.querySelectorAll('.dh-filter').forEach(x=>x.classList.toggle('active',x===b));apply()});
 body.querySelector('[data-dh-search]').oninput=e=>{query=e.target.value.trim().toLowerCase();apply()};
 body.querySelectorAll('[data-view-records]').forEach(btn=>btn.onclick=async()=>{const key=btn.dataset.viewRecords,box=body.querySelector(`[data-detail-box="${CSS.escape(key)}"]`);if(box.style.display==='block'){box.style.display='none';btn.textContent='View affected records →';return}box.style.display='block';box.innerHTML=`<div style="padding:13px;color:${C.soft};font-size:11px">Loading affected records…</div>`;btn.textContent='Hide records';try{renderDetails(box,await fetchDetails(key))}catch(e){box.innerHTML=`<div style="padding:13px;color:${C.danger};font-size:11px;font-weight:800">${esc(e.message)}</div>`}});
 apply();
}

async function load(body,refresh){render(body,null,null);if(refresh){refresh.disabled=true;refresh.style.opacity='.55'}try{render(body,await fetchHealth(),null)}catch(e){render(body,null,e.message||'Could not load Data Health.')}finally{if(refresh){refresh.disabled=false;refresh.style.opacity='1'}}}

function openDataHealth(){close();const o=document.createElement('div');o.id='engage-data-health-overlay';o.style.cssText='position:fixed;inset:0;z-index:100000;background:rgba(17,24,39,.48);display:flex;align-items:center;justify-content:center;padding:18px;box-sizing:border-box';o.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(900px,100%);max-height:min(90vh,900px);background:${C.paper};border-radius:20px;box-shadow:0 30px 90px rgba(0,0,0,.25);display:flex;flex-direction:column;overflow:hidden"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid ${C.line};background:#fff"><div><div style="display:flex;align-items:center;gap:8px"><div style="font-size:17px;font-weight:950;color:${C.ink}">Data Health</div><span style="font-size:8.5px;font-weight:900;text-transform:uppercase;letter-spacing:.5px;padding:3px 6px;border-radius:999px;background:${C.routeSoft};color:${C.route}">Control Centre</span></div><div style="font-size:11.5px;color:${C.soft};margin-top:2px">Live integrity, consistency and system checks for Engage</div></div><div style="display:flex;gap:8px"><button data-dh-refresh style="border:1px solid ${C.line};background:#fff;color:${C.ink};border-radius:9px;padding:7px 10px;font-weight:850;font-size:11px;cursor:pointer">↻ Refresh</button><button data-dh-close aria-label="Close" style="width:32px;height:32px;border:1px solid ${C.line};background:#fff;color:${C.ink};border-radius:9px;font-size:18px;cursor:pointer">×</button></div></div><div data-dh-body style="padding:16px;overflow:auto"></div></div>`;document.body.appendChild(o);const body=o.querySelector('[data-dh-body]'),refresh=o.querySelector('[data-dh-refresh]');o.querySelector('[data-dh-close]').onclick=close;o.onclick=e=>{if(e.target===o)close()};refresh.onclick=()=>load(body,refresh);load(body,refresh)}

function installButton(){if(getSession()?.role!=='admin')return;const crm=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='CRM Settings');if(!crm||document.getElementById('engage-data-health-button'))return;const b=document.createElement('button');b.id='engage-data-health-button';b.type='button';b.style.cssText=buttonStyle();b.innerHTML='<span style="font-size:14px">✓</span><span>Data Health</span>';b.onclick=openDataHealth;crm.insertAdjacentElement('afterend',b);crm.style.marginBottom='12px'}
const observer=new MutationObserver(installButton);observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',installButton);setTimeout(installButton,0);
