import React,{useEffect,useState} from 'react';
import {api,getSession} from './api.js';
import {OnboardingDialog} from './Onboarding.jsx';
import './quotations.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function EmployeeSettings({employee,isActive=true,onClose,onEdit,onDelete,onToggleActive}){
 const [p,setP]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(''),[reload,setReload]=useState(0);
 const month=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit'}).format(new Date())+'-01';
 const [targetMonth,setTargetMonth]=useState(month()),[target,setTarget]=useState(null),[targetSaved,setTargetSaved]=useState('');
 useEffect(()=>{let live=true;api.employeeClosingPermissions(employee.id).then(v=>{if(live){setP(v);setError('')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employee.id,reload]);
 useEffect(()=>{let live=true;api.performanceTargets({month:targetMonth}).then(v=>{if(!live)return;const x=(v.targets||[]).find(t=>t.salesman_id===employee.id)||{};setTarget({visits_target:x.visits_target||0,leads_target:x.leads_target||0,demos_target:x.demos_target||0,won_target:x.won_target||0,sales_value_target:x.sales_value_target||0,visits_incentive:x.visits_incentive||0,leads_incentive:x.leads_incentive||0,demos_incentive:x.demos_incentive||0,won_incentive:x.won_incentive||0,sales_value_incentive_pct:x.sales_value_incentive_pct||0});setTargetSaved('')}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employee.id,targetMonth]);
 return <OnboardingDialog title={`Employee Settings — ${employee.name||employee.fullName||'Employee'}`} onClose={onClose} busy={busy}><div className="ft-q"><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={busy} onClick={onEdit}>Edit employee</button>{onToggleActive&&<button disabled={busy} onClick={onToggleActive}>{isActive?'Deactivate employee':'Reactivate employee'}</button>}</div><h3>Day Closing permissions</h3>{error&&<p role="alert">{error} <button onClick={()=>setReload(v=>v+1)}>Reload</button></p>}{p?<><p className="ft-ob-muted">These permissions apply only to this employee.</p>{[['require_closing','Require Day Closing before End Day'],['allow_skip','Allow salesman to skip Day Closing'],['require_skip_reason','Require reason when skipped'],['allow_multiple_starts','Allow multiple Start Day / End Day cycles per day'],['allow_lead_without_start_day','Allow lead entry without Start Day / GPS']].map(([k,label])=><label className="ft-q-check" key={k}><input type="checkbox" role="switch" checked={!!p[k]} disabled={busy} onChange={e=>{setP(v=>({...v,[k]:e.target.checked}));setSaved('')}}/><span>{label} — <strong>{p[k]?'ON':'OFF'}</strong></span></label>)}<p className="ft-ob-muted">When closing is optional, the employee can end their day without a report. Skip permission controls whether Skip Day Closing is available. If Allow skip is ON and Require reason is ON, the salesman must enter a reason before Skip & End Day can succeed. Multiple starts lets this employee begin a new day after ending one, as many times as needed — useful for split shifts. Lead entry without Start Day / GPS is intended for trusted employees: when ON, this employee can add leads without starting the day and the lead does not require GPS.</p><button className="ft-ob-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setP(await api.saveEmployeeClosingPermissions(employee.id,p));setSaved('Permissions saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Save permissions</button>{saved&&<p role="status">{saved}</p>}</>:!error&&<p>Loading permissions…</p>}<div className="ft-q-box" style={{marginTop:18}}>
<h3>Targets &amp; Incentives</h3>
<p className="ft-ob-muted">Monthly targets are admin-only. Incentive is calculated only on achievement above the target.</p>
<label className="ft-ob-field">Month<input type="month" value={targetMonth.slice(0,7)} onChange={e=>setTargetMonth(e.target.value+'-01')}/></label>
{target&&<div>
{[
 ['Restaurant visits','visits_target','visits_incentive','₹ per extra visit'],
 ['New leads','leads_target','leads_incentive','₹ per extra lead'],
 ['Demos','demos_target','demos_incentive','₹ per extra demo'],
 ['Deals won','won_target','won_incentive','₹ per extra deal']
].map(([label,tk,ik,il])=><div key={tk} style={{padding:'10px 0',borderBottom:'1px solid #e6ece9'}}>
 <strong>{label}</strong>
 <div className="ft-q-grid" style={{marginTop:6}}>
  <label className="ft-ob-field">Monthly target<input type="number" min="0" value={target[tk]} onChange={e=>setTarget(v=>({...v,[tk]:e.target.value}))}/></label>
  <label className="ft-ob-field">{il}<input type="number" min="0" value={target[ik]} onChange={e=>setTarget(v=>({...v,[ik]:e.target.value}))}/></label>
 </div>
</div>)}
<div style={{padding:'10px 0'}}>
 <strong>Sales value</strong>
 <div className="ft-q-grid" style={{marginTop:6}}>
  <label className="ft-ob-field">Monthly target ₹<input type="number" min="0" value={target.sales_value_target} onChange={e=>setTarget(v=>({...v,sales_value_target:e.target.value}))}/></label>
  <label className="ft-ob-field">% on value above target<input type="number" min="0" step="0.1" value={target.sales_value_incentive_pct} onChange={e=>setTarget(v=>({...v,sales_value_incentive_pct:e.target.value}))}/></label>
 </div>
</div>
<button className="ft-ob-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api.savePerformanceTarget(employee.id,{month:targetMonth,...target});setTargetSaved('Targets & incentives saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Save targets &amp; incentives</button>
{targetSaved&&<p role="status">{targetSaved}</p>}
</div>}
</div>
<div className="ft-q-box"><button className="ft-q-danger" disabled={busy} onClick={onDelete}>Delete employee</button></div></div></OnboardingDialog>
}
export function DayClosingForm({onClose,onEnd}){
 const [data,setData]=useState(null),[values,setValues]=useState({outcomes:'',blockers:'',priorities:''}),[reason,setReason]=useState(''),[skipping,setSkipping]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;api.currentClosing().then(v=>{if(live){setData(v);if(!reload)setValues({outcomes:v.report?.outcomes||'',blockers:v.report?.blockers||'',priorities:v.report?.priorities||''});setError('')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[reload]);
 const body=()=>({...values,attendanceId:data.attendance.id,version:data.report?.version||0});
 const end=async mode=>{setBusy(true);setError('');try{await onEnd({...body(),mode,skipReason:reason})}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <OnboardingDialog title="Day Closing" onClose={onClose} busy={busy}><div className="ft-q">{error&&<div role="alert" className="ft-ob-error">{error}<button disabled={busy} onClick={()=>setReload(v=>v+1)}>Refresh permissions / report</button></div>}{!data&&!error&&<p>Loading…</p>}{data&&<><p className="ft-ob-muted">{data.attendance.day} · IST · {data.permissions.require_closing?'Closing report required':'Closing report optional'}</p><div className="ft-q-box"><h3>Recorded activity</h3><div className="ft-q-grid">{[['leads','Leads added'],['tasks','Tasks completed'],['quotes','Quotes marked sent'],['won','Deals marked won']].map(([k,label])=><div key={k}><strong>{data.metrics[k]||0}</strong> {label}</div>)}</div></div><form onSubmit={e=>{e.preventDefault();end('submit')}}>{[['outcomes','Main outcomes'],['blockers','Blockers / help needed (optional)'],['priorities','Tomorrow’s priorities']].map(([k,label])=><label className="ft-ob-field" key={k}>{label}<textarea maxLength={2000} required={k!=='blockers'} value={values[k]} disabled={busy} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/></label>)}<div className="ft-ob-actions"><button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await api.saveClosingDraft(body());setData(v=>({...v,report:r}));setMessage('Draft saved. Your day is still active.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Save draft</button><button className="ft-ob-primary" disabled={busy}>Submit report &amp; End Day</button></div></form>{!data.permissions.require_closing?<button disabled={busy} onClick={()=>end('none')}>End Day without report</button>:data.permissions.allow_skip&&<><button disabled={busy} onClick={()=>setSkipping(v=>!v)}>Skip Day Closing</button>{skipping&&<form className="ft-q-box" onSubmit={e=>{e.preventDefault();end('skip')}}><label className="ft-ob-field">Reason for skipping {data.permissions.require_skip_reason?'(required)':'(optional)'}<textarea required={data.permissions.require_skip_reason} maxLength={1000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Confirm skip &amp; End Day</button></form>}</>}{message&&<p role="status">{message}</p>}</>}</div></OnboardingDialog>
}
export function DayClosingReports({onClose}){
 const admin=getSession()?.role==='admin';const [date,setDate]=useState(today()),[employee,setEmployee]=useState(''),[employees,setEmployees]=useState([]),[reports,setReports]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 useEffect(()=>{if(!admin)return;let live=true;api.adminSalesmen().then(v=>{if(live)setEmployees(v.salesmen||[])}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[admin]);
 useEffect(()=>{if(!date)return;let live=true;setLoading(true);setSelected(null);api.closingReports({day:date,employee,offset}).then(v=>{if(live){setReports(v.reports);setMore(v.hasMore);setError('')}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[date,employee,offset]);
 const label=r=>({submitted:'Submitted',skipped:'Skipped',not_required:'Not required',draft:'Draft — not submitted'})[r.status]||'Not submitted';
 return <OnboardingDialog title={admin?'Day Closing reports':'My Daily Reports'} onClose={onClose}><div className="ft-q"><div className="ft-q-grid"><label className="ft-ob-field">Date · IST<input type="date" required value={date} onChange={e=>{setDate(e.target.value);setOffset(0)}}/></label>{admin&&<label className="ft-ob-field">Employee<select value={employee} onChange={e=>{setEmployee(e.target.value);setOffset(0)}}><option value="">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>}</div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading…</p>:reports.map((r,i)=><button className="ft-ob-customer" key={r.attendance_id||r.user_id} onClick={()=>setSelected(i)}><strong>{r.full_name}{r.session_number>1?` · Session ${r.session_number}`:''}</strong><span>{label(r)} · {r.end_day_at?'Day ended':r.start_day_at?'Day active':'Day not started'}</span></button>)}{!loading&&!reports.length&&<p>No records for this date.</p>}{selected!==null&&reports[selected]&&<div className="ft-q-box"><h3>{reports[selected].full_name} · {label(reports[selected])}</h3>{[['outcomes','Outcomes'],['blockers','Blockers'],['priorities','Tomorrow’s priorities'],['skip_reason','Skip reason']].map(([k,label])=>reports[selected][k]&&<div key={k}><strong>{label}</strong><p className="ft-q-text">{reports[selected][k]}</p></div>)}{reports[selected].metrics&&<p className="ft-ob-muted">{reports[selected].metrics.leads||0} leads added · {reports[selected].metrics.tasks||0} tasks completed · {reports[selected].metrics.quotes||0} quotes marked sent · {reports[selected].metrics.won||0} deals marked won</p>}</div>}<div className="ft-ob-actions">{offset>0&&<button onClick={()=>setOffset(v=>v-50)}>Previous</button>}{more&&<button onClick={()=>setOffset(v=>v+50)}>Next</button>}</div></div></OnboardingDialog>
}
export function DayClosingReportsEntry(){const [open,setOpen]=useState(false);return <><button type="button" onClick={()=>setOpen(true)} style={{padding:12,border:'1px solid #dce5df',borderRadius:10,background:'#fff',color:'#205b5b',fontWeight:600,marginBottom:14}}>Day Closing reports</button>{open&&<DayClosingReports onClose={()=>setOpen(false)}/>}</>}
