import React,{useEffect,useState} from 'react';
import {api,getSession} from './api.js';
import {OnboardingDialog} from './Onboarding.jsx';
import './quotations.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function EmployeeSettings({employee,isActive=true,onClose,onEdit,onDelete,onToggleActive}){
 const [p,setP]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(''),[reload,setReload]=useState(0);
 const month=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit'}).format(new Date())+'-01';
 const [targetMonth,setTargetMonth]=useState(month()),[target,setTarget]=useState(null),[targetSaved,setTargetSaved]=useState(''),[targetError,setTargetError]=useState('');
 const currentYear=new Date().getFullYear();
 const [planYear,setPlanYear]=useState(currentYear),[incentive,setIncentive]=useState(null),[incentiveSaved,setIncentiveSaved]=useState(''),[incentiveError,setIncentiveError]=useState('');
 useEffect(()=>{let live=true;api.employeeClosingPermissions(employee.id).then(v=>{if(live){setP(v);setError('')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employee.id,reload]);
 useEffect(()=>{let live=true;setTargetError('');api.performanceTargets({month:targetMonth}).then(v=>{if(!live)return;const x=(v.targets||[]).find(t=>t.salesman_id===employee.id)||{};setTarget({visits_target:x.visits_target||0,leads_target:x.leads_target||0,demos_target:x.demos_target||0,won_target:x.won_target||0,sales_value_target:x.sales_value_target||0,visits_incentive:x.visits_incentive||0,leads_incentive:x.leads_incentive||0,demos_incentive:x.demos_incentive||0,won_incentive:x.won_incentive||0,sales_value_incentive_pct:x.sales_value_incentive_pct||0});setTargetSaved('')}).catch(e=>{if(live)setTargetError(e.message||"Couldn't load targets.")});return()=>{live=false}},[employee.id,targetMonth]);
 useEffect(()=>{let live=true;setIncentiveError('');api.incentivePlan(employee.id,planYear).then(v=>{if(live){setIncentive(v.plan);setIncentiveSaved('')}}).catch(e=>{if(live)setIncentiveError(e.message||"Couldn't load incentive plan.")});return()=>{live=false}},[employee.id,planYear]);
 const [tab,setTab]=useState('general');
 const tabButton=(key,label)=><button type="button" onClick={()=>setTab(key)} style={{flex:1,minWidth:105,border:0,borderRadius:9,padding:'9px 10px',fontSize:11.5,fontWeight:750,cursor:'pointer',background:tab===key?'#fff':'transparent',color:tab===key?'#145C5D':'#64706b',boxShadow:tab===key?'0 1px 4px rgba(20,40,35,.09)':'none'}}>{label}</button>;
 return <OnboardingDialog title={`Employee Settings — ${employee.name||employee.fullName||'Employee'}`} onClose={onClose} busy={busy}><div className="ft-q">
  <div style={{display:'flex',gap:4,padding:4,background:'#f1f5f3',borderRadius:12,marginBottom:18,overflowX:'auto'}}>{tabButton('general','General')}{tabButton('work','Work Rules')}{tabButton('targets','Targets & Incentives')}</div>

  {tab==='general'&&<>
   <div className="ft-q-box"><div style={{fontSize:11,fontWeight:800,letterSpacing:.6,color:'#7a8580',marginBottom:10}}>EMPLOYEE</div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}}><div><div style={{fontSize:17,fontWeight:800}}>{employee.name||employee.fullName||'Employee'}</div><div className="ft-ob-muted" style={{marginTop:3}}>Salesman · {isActive?'Active':'Inactive'}</div></div><button disabled={busy} onClick={onEdit}>Edit employee</button></div></div>
   <div className="ft-q-box" style={{marginTop:18,borderColor:'#ead8d8'}}><div style={{fontSize:11,fontWeight:800,letterSpacing:.6,color:'#a14b4b',marginBottom:8}}>DANGER ZONE</div><p className="ft-ob-muted">Employee access and deletion controls.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{onToggleActive&&<button disabled={busy} onClick={onToggleActive}>{isActive?'Deactivate employee':'Reactivate employee'}</button>}<button className="ft-q-danger" disabled={busy} onClick={onDelete}>Delete employee</button></div></div>
  </>}

  {tab==='work'&&<>
   <div className="ft-q-box"><h3 style={{marginTop:0}}>Day Closing</h3>{error&&<p role="alert">{error} <button onClick={()=>setReload(v=>v+1)}>Reload</button></p>}{p?<><p className="ft-ob-muted">Control how this employee starts, works and ends the day.</p>{[['require_closing','Require Day Closing before End Day'],['allow_skip','Allow salesman to skip Day Closing'],['require_skip_reason','Require reason when skipped'],['allow_multiple_starts','Allow multiple Start Day / End Day cycles per day']].map(([k,label])=><label className="ft-q-check" key={k}><input type="checkbox" role="switch" checked={!!p[k]} disabled={busy} onChange={e=>{setP(v=>({...v,[k]:e.target.checked}));setSaved('')}}/><span>{label} — <strong>{p[k]?'ON':'OFF'}</strong></span></label>)}</>:!error&&<p>Loading permissions…</p>}</div>
   {p&&<div className="ft-q-box" style={{marginTop:14}}><h3 style={{marginTop:0}}>Lead Permissions</h3><label className="ft-q-check"><input type="checkbox" role="switch" checked={!!p.allow_lead_without_start_day} disabled={busy} onChange={e=>{setP(v=>({...v,allow_lead_without_start_day:e.target.checked}));setSaved('')}}/><span>Allow lead entry without Start Day / GPS — <strong>{p.allow_lead_without_start_day?'ON':'OFF'}</strong></span></label><p className="ft-ob-muted">Use this only for trusted employees who may add leads without starting their day or capturing GPS.</p></div>}
   {p&&<><button className="ft-ob-primary" style={{marginTop:14}} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setP(await api.saveEmployeeClosingPermissions(employee.id,p));setSaved('Work rules saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Save Work Rules</button>{saved&&<p role="status">{saved}</p>}</>}
  </>}

  {tab==='targets'&&<>
   <div className="ft-q-box"><h3 style={{margin:'0 0 4px'}}>Performance Targets</h3><p className="ft-ob-muted" style={{marginTop:0}}>Monthly expectations. Visits, leads and demos do not earn incentives.</p><label className="ft-ob-field">Month<input type="month" value={targetMonth.slice(0,7)} onChange={e=>setTargetMonth(e.target.value+'-01')}/></label>{targetError&&<p role="alert">{targetError}</p>}{target&&<div><div className="ft-q-grid">{[['Restaurant visits','visits_target'],['New leads','leads_target'],['Demos','demos_target'],['Deals won','won_target'],['Sales value ₹','sales_value_target']].map(([label,key])=><label className="ft-ob-field" key={key}>{label}<input type="number" min="0" value={target[key]} onChange={e=>setTarget(v=>({...v,[key]:e.target.value}))}/></label>)}</div><button className="ft-ob-primary" disabled={busy} onClick={async()=>{setBusy(true);setTargetError('');try{await api.savePerformanceTarget(employee.id,{month:targetMonth,...target,visits_incentive:0,leads_incentive:0,demos_incentive:0,won_incentive:0,sales_value_incentive_pct:0});setTargetSaved('Monthly targets saved.')}catch(e){setTargetError(e.message)}finally{setBusy(false)}}}>Save Targets</button>{targetSaved&&<p role="status">{targetSaved}</p>}</div>}</div>
   <div className="ft-q-box" style={{marginTop:14}}><h3 style={{margin:'0 0 4px'}}>Incentive Settings</h3><p className="ft-ob-muted" style={{marginTop:0}}>Set once for the year. The same rules apply to every month's Deals Won and Sales Value targets.</p><label className="ft-ob-field">Effective year<select value={planYear} onChange={e=>setPlanYear(Number(e.target.value))}>{[currentYear-1,currentYear,currentYear+1,currentYear+2].map(y=><option key={y} value={y}>{y}</option>)}</select></label>{incentiveError&&<p role="alert">{incentiveError}</p>}{incentive&&<div>
    <div style={{padding:'12px 0',borderBottom:'1px solid #e6ece9'}}><label className="ft-q-check"><input type="checkbox" role="switch" checked={!!incentive.deals_enabled} onChange={e=>setIncentive(v=>({...v,deals_enabled:e.target.checked}))}/><span><strong>Deals Won incentive</strong> — {incentive.deals_enabled?'ON':'OFF'}</span></label>{incentive.deals_enabled&&<label className="ft-ob-field">₹ per additional deal above monthly target<input type="number" min="0" value={incentive.deal_extra_amount||0} onChange={e=>setIncentive(v=>({...v,deal_extra_amount:e.target.value}))}/></label>}</div>
    <div style={{padding:'12px 0'}}><label className="ft-q-check"><input type="checkbox" role="switch" checked={!!incentive.sales_enabled} onChange={e=>setIncentive(v=>({...v,sales_enabled:e.target.checked}))}/><span><strong>Sales Value incentive</strong> — {incentive.sales_enabled?'ON':'OFF'}</span></label>{incentive.sales_enabled&&<label className="ft-ob-field">% on sales above monthly target<input type="number" min="0" step="0.1" value={incentive.sales_value_extra_pct||0} onChange={e=>setIncentive(v=>({...v,sales_value_extra_pct:e.target.value}))}/></label>}</div>
    <div style={{padding:'10px 12px',background:'#f5f8f7',borderRadius:10,fontSize:12,lineHeight:1.55}}>Monthly targets can change. Incentive rates stay the same for the selected year and apply only above each month's target.</div>
    <button className="ft-ob-primary" style={{marginTop:12}} disabled={busy} onClick={async()=>{setBusy(true);setIncentiveError('');try{await api.saveIncentivePlan(employee.id,{...incentive,plan_year:planYear});setIncentiveSaved('Incentive settings saved for all months in '+planYear+'.')}catch(e){setIncentiveError(e.message)}finally{setBusy(false)}}}>Save Incentive Settings</button>{incentiveSaved&&<p role="status">{incentiveSaved}</p>}
   </div>}</div>
  </>}
 </div></OnboardingDialog>
}