import React,{useEffect,useMemo,useState}from'react';import{api}from'./api.js';import{ChevronDown,ChevronUp,Download,Users,MapPin,UserPlus,Footprints,Clock3}from'lucide-react';
const C={ink:'#1A1D23',soft:'#6B7280',line:'#E7E9EE',card:'#fff',green:'#12805C',amber:'#B8791F',blue:'#2563EB'};
const istDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const tm=v=>v?new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}):'—';
const dur=(a,b,day)=>{if(!a)return'—';const s=new Date(a).getTime(),e=b?new Date(b).getTime():(day===istDay()?Date.now():s);const m=Math.max(0,Math.floor((e-s)/60000)),h=Math.floor(m/60);return h?`${h}h ${m%60}m`:`${m}m`;};
const pill=(txt,tone)=>{const x=tone==='green'?['#E8F5EF','#147A5A']:tone==='amber'?['#FFF5E8','#9A611A']:['#F2F4F7','#667085'];return <span style={{background:x[0],color:x[1],padding:'5px 8px',borderRadius:999,fontSize:11,fontWeight:800,whiteSpace:'nowrap'}}>{txt}</span>};
export default function EnhancedDailyActivityReport({salesmen=[]}){const[date,setDate]=useState(istDay()),[employee,setEmployee]=useState(''),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(null),[brief,setBrief]=useState(null),[briefLoading,setBriefLoading]=useState(false);
useEffect(()=>{let alive=true;setLoading(true);setError('');api.adminReportDailyActivity({date,...(employee?{salesmanId:employee}:{})}).then(r=>{if(alive)setRows(r.salesmen||[])}).catch(e=>alive&&setError(e.message||'Could not load daily activity.')).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[date,employee]);
const summary=useMemo(()=>({employees:rows.filter(r=>r.dayStarted).length,visits:rows.reduce((n,r)=>n+Number(r.visitCount||0),0),leads:rows.reduce((n,r)=>n+Number(r.leadsCount||0),0),distance:rows.reduce((n,r)=>n+Number(r.distanceKm||0),0)}),[rows]);
const toggle=async r=>{if(open===r.salesmanId){setOpen(null);setBrief(null);return}setOpen(r.salesmanId);setBrief(null);setBriefLoading(true);try{setBrief(await api.adminSalesmanBrief(r.salesmanId,date))}catch(e){setBrief({error:e.message||'Could not load activity details.'})}finally{setBriefLoading(false)}};
const exportCsv=()=>{const head=['Employee','Start Day','End Day','Working Duration','Visits','Leads Added','Distance Km','Status'];const body=rows.map(r=>[r.salesmanName,tm(r.dayStarted),tm(r.dayEnded),dur(r.dayStarted,r.dayEnded,date),r.visitCount,r.leadsCount,Number(r.distanceKm||0).toFixed(1),!r.dayStarted?'Not Started':r.dayEnded?'Completed':'Day Open']);const csv=[head,...body].map(x=>x.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`daily-activity-${date}.csv`;a.click();URL.revokeObjectURL(a.href)};
return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:12,flexWrap:'wrap',marginBottom:16}}><div><div style={{fontSize:12.5,color:C.soft,marginBottom:3}}>Track field activity, visits and lead creation by employee</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input type='date' value={date} onChange={e=>setDate(e.target.value)} style={{height:40,border:`1px solid ${C.line}`,borderRadius:10,padding:'0 11px',background:'#fff'}}/><select value={employee} onChange={e=>setEmployee(e.target.value)} style={{height:40,minWidth:175,border:`1px solid ${C.line}`,borderRadius:10,padding:'0 32px 0 11px',background:'#fff'}}><option value=''>All Employees</option>{salesmen.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={exportCsv} disabled={!rows.length} style={{height:40,border:`1px solid ${C.line}`,borderRadius:10,padding:'0 13px',background:'#fff',fontWeight:700,display:'flex',alignItems:'center',gap:7,cursor:'pointer'}}><Download size={15}/> Export</button></div></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(140px,1fr))',gap:10,marginBottom:16,overflowX:'auto'}}>{[[Users,'Employees active',summary.employees,C.green],[Footprints,'Visits',summary.visits,C.blue],[UserPlus,'Leads added',summary.leads,C.green],[MapPin,'Distance',`${summary.distance.toFixed(1)} km`,C.amber]].map(([I,l,v,c])=><div key={l} style={{background:C.card,border:`1px solid ${C.line}`,borderRadius:13,padding:'13px 14px',minWidth:140}}><div style={{display:'flex',alignItems:'center',gap:7,color:C.soft,fontSize:11,fontWeight:800}}><I size={14}/>{l}</div><div style={{fontSize:23,fontWeight:850,color:c,marginTop:5}}>{v}</div></div>)}</div>
{error&&<div style={{padding:'11px 12px',borderRadius:10,background:'#FDECEC',color:'#A32929',fontSize:12.5,marginBottom:12}}>{error}</div>}
<div style={{background:C.card,border:`1px solid ${C.line}`,borderRadius:14,overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:980}}><thead><tr style={{background:'#FBFCFD'}}>{['Employee','Start Day','End Day','Working','Visits','Leads','Distance','Status',''].map(h=><th key={h} style={{textAlign:'left',padding:'11px 12px',fontSize:10.5,textTransform:'uppercase',letterSpacing:.35,color:C.soft,borderBottom:`1px solid ${C.line}`}}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={9} style={{padding:30,textAlign:'center',color:C.soft}}>Loading daily activity…</td></tr>:rows.length?rows.map(r=>{const status=!r.dayStarted?'Not Started':r.dayEnded?'Completed':'Day Open';return <React.Fragment key={r.salesmanId}><tr onClick={()=>toggle(r)} style={{cursor:'pointer'}}><td style={td}><strong>{r.salesmanName}</strong></td><td style={td}>{tm(r.dayStarted)}</td><td style={td}>{tm(r.dayEnded)}</td><td style={td}>{dur(r.dayStarted,r.dayEnded,date)}</td><td style={td}>{r.visitCount}</td><td style={td}>{r.leadsCount}</td><td style={td}>{Number(r.distanceKm||0).toFixed(1)} km</td><td style={td}>{status==='Completed'?pill(status,'green'):status==='Day Open'?pill(status,'amber'):pill(status,'gray')}</td><td style={td}>{open===r.salesmanId?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</td></tr>{open===r.salesmanId&&<tr><td colSpan={9} style={{padding:0,background:'#FBFCFD',borderBottom:`1px solid ${C.line}`}}>{briefLoading?<div style={{padding:18,color:C.soft}}>Loading activity timeline…</div>:brief?.error?<div style={{padding:18,color:'#A32929'}}>{brief.error}</div>:brief?<div style={{padding:16}}><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(120px,1fr))',gap:8,marginBottom:14}}>{[['Visits',brief.summary?.visits||0],['Leads added',brief.summary?.leadsAdded||0],['Follow-ups',brief.summary?.followUpsCompleted||0],['Distance',`${brief.summary?.distanceKm||0} km`]].map(([l,v])=><div key={l} style={{background:'#fff',border:`1px solid ${C.line}`,borderRadius:10,padding:'10px 11px'}}><div style={{fontSize:10.5,color:C.soft,fontWeight:700}}>{l}</div><div style={{fontSize:17,fontWeight:850,marginTop:3}}>{v}</div></div>)}</div><div style={{fontSize:12,fontWeight:800,marginBottom:8,display:'flex',alignItems:'center',gap:6}}><Clock3 size={14}/> Activity timeline</div>{brief.events?.length?<div style={{display:'grid',gap:8}}>{brief.events.map((e,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'82px 1fr',gap:10,fontSize:12.5}}><span style={{color:C.soft}}>{tm(e.at)}</span><span>{e.text}</span></div>)}</div>:<div style={{fontSize:12.5,color:C.soft}}>No recorded activity for this employee on this date.</div>}</div>:null}</td></tr>}</React.Fragment>}):<tr><td colSpan={9} style={{padding:30,textAlign:'center',color:C.soft}}>No activity records found.</td></tr>}</tbody></table></div></div></div>}
const td={padding:'12px',borderBottom:`1px solid ${C.line}`,fontSize:12.5,color:C.ink,verticalAlign:'middle'};
