import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Menu, Settings, ListChecks, FileText, CheckCheck, X } from 'lucide-react';
import { api, getSession } from './api.js';
import './onboarding.css';

export function AppMenu({ signedIn, onSettings, onOnboarding, onQuotations, onApprovals }) {
 const [open,setOpen]=useState(false);const root=useRef(null),trigger=useRef(null);
 useEffect(()=>{if(!open)return;const outside=e=>{if(!root.current?.contains(e.target))setOpen(false)};const escape=e=>{if(e.key==='Escape'){e.stopPropagation();setOpen(false);trigger.current?.focus()}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open]);
 return <div className="ft-app-menu" ref={root}><button className="ft-app-menu-trigger" type="button" aria-label="Menu" title="Menu" aria-expanded={open} aria-controls="ft-app-menu-options" ref={trigger} onClick={()=>setOpen(v=>!v)}><Menu size={14}/></button>{open&&<nav id="ft-app-menu-options" className="ft-app-menu-options" aria-label="App menu">{signedIn&&<button type="button" onClick={()=>{setOpen(false);onOnboarding()}}><ListChecks size={15}/>Onboarding checklist</button>}{signedIn&&onQuotations&&<button type="button" onClick={()=>{setOpen(false);onQuotations()}}><FileText size={15}/>Quotations</button>}{signedIn&&onApprovals&&<button type="button" onClick={()=>{setOpen(false);onApprovals()}}><CheckCheck size={15}/>Quotation approvals</button>}<button type="button" onClick={()=>{setOpen(false);onSettings()}}><Settings size={15}/>Settings</button></nav>}</div>;
}

export function OnboardingDialog({title,onClose,children,busy}) {
 const panel=useRef(null),close=useRef(onClose),working=useRef(busy);close.current=onClose;working.current=busy;
 useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape'){e.stopPropagation();if(!working.current)close.current()}if(e.key==='Tab'){const controls=[...panel.current.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary')].filter(el=>el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key,true);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key,true);previous?.focus()}},[]);
 return createPortal(<div className="ft-onboarding-backdrop" onClick={e=>{e.stopPropagation();if(!busy)onClose()}}><section className="ft-onboarding" role="dialog" aria-modal="true" aria-labelledby="ft-onboarding-title" ref={panel} onClick={e=>e.stopPropagation()}><header><h2 id="ft-onboarding-title">{title}</h2><button type="button" aria-label={`Close ${title}`} onClick={onClose} disabled={busy}><X size={19}/></button></header>{children}</section></div>,document.body);
}
const date = value => new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})+' IST';

export default function OnboardingPanel({onClose}) {
 const admin=getSession()?.role==='admin';
 const [selected,setSelected]=useState(null),[record,setRecord]=useState(null),[customers,setCustomers]=useState([]),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[revision,setRevision]=useState(0);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[summary,setSummary]=useState(null),[phone,setPhone]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(0)},250);return()=>clearTimeout(timer)},[search]);
 useEffect(()=>{if(selected)return;let cancelled=false;setLoading(true);setError('');api.onboardingCustomers({offset:page*30,search:query}).then(r=>{if(!cancelled){setCustomers(r.customers);setHasMore(r.hasMore)}}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[selected,page,query,revision]);
 useEffect(()=>{if(!selected)return;let cancelled=false;setLoading(true);setRecord(null);setError('');api.onboardingGet(selected).then(r=>{if(!cancelled)setRecord(r.onboarding)}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[selected,revision]);
 const open=async customer=>{if(busy)return;setBusy(true);setError('');try{if(!customer.started)await api.onboardingStart(customer.id);setSelected(customer.id);setSummary(null)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const update=async(step,done,note)=>{if(busy)return;setBusy(true);setError('');try{const r=await api.onboardingUpdate(selected,step.id,{version:record.version,done,note});setRecord(r.onboarding);setSummary(null);window.dispatchEvent(new Event('fieldtrail:notifications-read'))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const share=async()=>{if(busy)return;setBusy(true);setError('');try{const r=await api.onboardingSummary(selected);setSummary(r.summary);const number=r.summary.phone.replace(/\D/g,'');setPhone(number.length===10?'91'+number:number)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const download=async()=>{if(busy)return;setBusy(true);setError('');try{const blob=await api.onboardingPDF(selected);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='swirl-onboarding-summary.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const completed=record?.steps.filter(s=>s.done).length||0;
 const validPhone=/^[1-9]\d{7,14}$/.test(phone);
 return <OnboardingDialog title={summary?'Review owner summary':'Customer onboarding'} onClose={onClose} busy={busy}>
 {selected&&<button className="ft-ob-back" disabled={busy} onClick={()=>{if(summary)setSummary(null);else{setSelected(null);setRecord(null)}setError('')}}>← {summary?'Back to checklist':'All customers'}</button>}
 {error&&<div className="ft-ob-error" role="alert"><p>{error}</p><button disabled={busy} onClick={()=>{setSummary(null);setRevision(v=>v+1)}}>Refresh</button></div>}
 {!selected&&<><p className="ft-ob-muted">{admin?'All customers':'Your customers'} · Won deals and existing checklists</p><label className="ft-ob-field">Find restaurant<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="Business name"/></label>{loading?<p role="status">Loading customers…</p>:!error&&<>{customers.length===0&&<p>No matching customers. Mark a deal Won to start its checklist.</p>}{customers.map(c=><button key={c.id} className="ft-ob-customer" disabled={busy} onClick={()=>open(c)}><strong>{c.business_name}</strong><span className="ft-ob-muted">{c.assignee_name||'Unassigned'} · {c.started?`${c.completed}/${c.total} completed`:'Start onboarding →'}</span></button>)}<div className="ft-ob-actions">{page>0&&<button disabled={busy} onClick={()=>setPage(v=>v-1)}>Previous</button>}{hasMore&&<button disabled={busy} onClick={()=>setPage(v=>v+1)}>Next</button>}</div></>}</>}
 {selected&&loading&&<p role="status">Loading checklist…</p>}
 {selected&&record&&!summary&&!loading&&<><div className="ft-ob-heading"><h3>{record.business_name}</h3><span className="ft-ob-badge">{completed===record.steps.length?'Ready to share':'In progress'}</span></div><progress value={completed} max={record.steps.length} aria-label="Onboarding completion"/><div className="ft-ob-muted" role="status">{completed} of {record.steps.length} completed</div>
 <div>{record.steps.map(step=><OnboardingStep key={step.id} step={step} busy={busy} onUpdate={update}/>)}</div>
 {admin?<><button className="ft-ob-primary" disabled={busy||completed!==record.steps.length} onClick={share}>Share completion summary</button><p className="ft-ob-muted">{completed===record.steps.length?'Review the owner summary before sharing.':'Complete every step to enable sharing.'}</p></>:<p className="ft-ob-muted">Admin can share the completion summary with the owner once every step is complete.</p>}</>}
 {summary&&<><h3>{summary.businessName}</h3><span className="ft-ob-badge">Setup checklist complete</span><pre className="ft-ob-summary">{summary.text}</pre><label className="ft-ob-field">Owner WhatsApp number (with country code)<input type="tel" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} placeholder="919876543210" maxLength={15}/></label><div className="ft-ob-actions">{validPhone?<a className="ft-ob-primary" href={`https://wa.me/${phone}?text=${encodeURIComponent(summary.text)}`} target="_blank" rel="noopener noreferrer">Open WhatsApp</a>:<button disabled>Open WhatsApp</button>}<button onClick={download} disabled={busy}>{busy?'Preparing…':'Download PDF'}</button></div><p className="ft-ob-muted">Review the number. WhatsApp opens with this message; you tap Send. The PDF contains completion steps and dates, without internal notes.</p></>}
 </OnboardingDialog>;
}
function OnboardingStep({step,busy,onUpdate}) {
 const [note,setNote]=useState(step.note||'');useEffect(()=>setNote(step.note||''),[step.note]);
 return <div className="ft-ob-step"><label><input type="checkbox" checked={step.done} disabled={busy} onChange={e=>onUpdate(step,e.target.checked,note)}/><span>{step.title}{step.completedAt&&<small>Completed {date(step.completedAt)}</small>}</span></label><details><summary>Internal note{step.note?' · Saved':''}</summary><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} disabled={busy} aria-label={`Note for ${step.title}`}/><button disabled={busy||note===(step.note||'')} onClick={()=>onUpdate(step,step.done,note)}>Save note</button></details></div>;
}
export function OnboardingTemplateEditor({onClose}) {
 const [sharing,setSharing]=useState({title:'',intro:'',closing:''});
 const [template,setTemplate]=useState(null),[steps,setSteps]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[saved,setSaved]=useState('');
 useEffect(()=>{let cancelled=false;setTemplate(null);setError('');api.onboardingTemplate().then(r=>{if(!cancelled){setTemplate(r);setSteps(r.steps);setSharing(r.sharing||{title:'Your restaurant is now live on Swirl!',intro:'Hello {owner}, your setup is complete and {restaurant} is now live on Swirl.',closing:'Thank you for choosing Swirl.\nTeam Swirl'})}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[revision]);
 const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setSaved('');try{const r=await api.onboardingSaveTemplate({version:template.version,steps,sharing});setTemplate(r);setSteps(r.steps);setSharing(r.sharing||{title:'Your restaurant is now live on Swirl!',intro:'Hello {owner}, your setup is complete and {restaurant} is now live on Swirl.',closing:'Thank you for choosing Swirl.\nTeam Swirl'});setSaved('Settings saved. Sharing text is updated; new checklists will use these steps.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const move=(index,delta)=>setSteps(current=>{const next=[...current];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next});
 return <OnboardingDialog title="Onboarding checklist settings" onClose={onClose} busy={busy}><p className="ft-ob-muted">Admin settings · Required steps for each new customer</p>{error&&<div role="alert" className="ft-ob-error"><p>{error}</p><button disabled={busy} onClick={()=>{setSaved('');setRevision(v=>v+1)}}>Reload saved template</button></div>}{!template&&!error&&<p role="status">Loading template…</p>}{template&&<form onSubmit={save}>{steps.map((step,index)=><div className="ft-ob-edit" key={step.id}><label>Step {index+1}<input required maxLength={160} value={step.title} disabled={busy} onChange={e=>setSteps(s=>s.map(v=>v.id===step.id?{...v,title:e.target.value}:v))}/></label><div className="ft-ob-actions"><button type="button" disabled={busy||index===0} aria-label={`Move step ${index+1} up`} onClick={()=>move(index,-1)}>↑</button><button type="button" disabled={busy||index===steps.length-1} aria-label={`Move step ${index+1} down`} onClick={()=>move(index,1)}>↓</button><button type="button" disabled={busy||steps.length===1} onClick={()=>setSteps(s=>s.filter(v=>v.id!==step.id))}>Remove</button></div></div>)}<div className="ft-ob-actions"><button type="button" disabled={busy||steps.length>=30} onClick={()=>setSteps(s=>[...s,{id:crypto.randomUUID(),title:''}])}>+ Add step</button></div><p className="ft-ob-notice">Changes apply to new checklists only. Existing customers keep their steps and progress.</p><h3>WhatsApp &amp; PDF wording</h3><p className="ft-ob-muted">Use {'{restaurant}'} and {'{owner}'} for automatic names. The completed checklist and dates are added automatically.</p>{[['title','Heading',120],['intro','Opening message',1000],['closing','Closing message / support contact',1000]].map(([key,label,max])=><label className="ft-ob-field" key={key}>{label}<textarea required maxLength={max} value={sharing[key]} disabled={busy} onChange={e=>setSharing(v=>({...v,[key]:e.target.value}))}/></label>)}<p className="ft-ob-notice">Wording changes apply to newly generated WhatsApp messages and PDFs for all customers. They do not change previously shared copies. Use “live” wording only after the account is actually live.</p><details><summary>Preview with sample names</summary><pre className="ft-ob-summary">{[sharing.title,sharing.intro,'✓ Completed checklist steps\nCompleted: [completion date]',sharing.closing].join('\n\n').replace(/\{restaurant\}/g,'Dubai Darbar').replace(/\{owner\}/g,'Ahmed')}</pre></details><button className="ft-ob-primary" disabled={busy}>{busy?'Saving…':'Save settings'}</button>{saved&&<p role="status">{saved}</p>}</form>}</OnboardingDialog>;
}
